```{r context-message}
write(formats2h2("Generate the context subsection"), stderr())
```

`r h1_context`

```{r context-load-facilities, results='asis'}
facilities <- params$research_facilities
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  facilities <- facilities[, c("lvl2", "facility_id", "facility_name", "training_date", "rollout_date")]
} else if (Sys.getenv('TIMCI_COUNTRY') == 'Kenya') {
  facilities <- facilities[, c("lvl2", "facility_id", "facility_name", "type", "training_date", "rollout_date")]
} else{
  facilities <- facilities[, c("lvl2", "facility_id", "facility_name", "type", "intervention")]
}
facilities <- facilities[!duplicated(facilities$facility_id), ]
```

```{r context-format-facility-info, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  # Sort by district and rename columns
  facility_disp <- facilities %>%
    dplyr::arrange(lvl2) %>%
    dplyr::rename('District sanitaire' = 'lvl2',
                  'ID' = 'facility_id',
                  'Poste de santé' = 'facility_name',
                  "Fin pré-intervention" = 'training_date',
                  "Début post-intervention" = 'rollout_date')
} else if(Sys.getenv('TIMCI_COUNTRY') == 'Kenya'){
  # Sort by County then type of facility
  facility_disp <- facilities %>%
    dplyr::arrange(lvl2, type) %>%
    dplyr::rename('County' = 'lvl2',
                  'ID' = 'facility_id',
                  'Facility' = 'facility_name',
                  'Type' = 'type',
                  "Baseline end" = 'training_date',
                  "Roll-out date" = 'rollout_date')
  
} else{
  # Sort by district then type of facility
  facility_disp <- facilities %>%
    dplyr::arrange(lvl2, type) %>%
    dplyr::rename('District' = 'lvl2',
                  'ID' = 'facility_id',
                  'Facility' = 'facility_name',
                  'Type' = 'type')
}
```

```{r}
facility_nb <- nrow(facilities)
```

```{r context-facility-type, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania' || Sys.getenv('TIMCI_COUNTRY') == 'Kenya') {
  facilities$type <- tolower(facilities$type)
  hc_nb <- nrow(facilities %>% filter(type == "health center"))
  dispensary_nb <- nrow(facilities %>% filter(type == "dispensary"))
  cat(paste0("**", facility_nb, "** research facilities, among which **", hc_nb, "** health centres and **", dispensary_nb, "** dispensaries"))
} else if (Sys.getenv('TIMCI_COUNTRY') == 'India') {
  hc_nb <- nrow(facilities %>% filter(type == "CHC"))
  dispensary_nb <- nrow(facilities %>% filter(type == "PHC"))
  cat(paste0("**", facility_nb, "** research facilities, among which **", hc_nb, "** community health centres (CHCs) and **", dispensary_nb, "** primary health centres (PHCs)"))
} else if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal'){
  cat(paste0("**", facility_nb, "** postes de recherche"))
} else{
  cat(paste0("**", facility_nb, "** research facilities"))
}
```

```{r context-diplay-facility-table, results = "asis"}
facility_disp  %>% 
  kableExtra::kbl(booktabs = TRUE,
                  longtable = TRUE, 
                  linesep = "",
                  caption = facility_cap,
                  align = c("c", "c", "c")) %>% 
  kableExtra::kable_styling(latex_options = c("HOLD_position", "repeat_header"),
                            font_size = table_fs) %>%
  kableExtra::row_spec(0, color = total_row_ft2, background = total_row_bg2, bold = TRUE) %>%
  kableExtra::collapse_rows(columns = 1, valign = "top") 
```

```{r}
if (Sys.getenv('TIMCI_COUNTRY') == "Kenya") {
  hc_enrolment_target <- 8
  dispensary_enrolment_target <- 4
  day_target <- dispensary_enrolment_target * dispensary_nb + hc_enrolment_target * hc_nb
  enrolment_target <- round(day_target / facility_nb, 0)
} else if (Sys.getenv('TIMCI_COUNTRY') == "Senegal") {
  enrolment_target <- 4
} else if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania") {
  hc_enrolment_target <- 16
  dispensary_enrolment_target <- 4
  day_target <- dispensary_enrolment_target * dispensary_nb + hc_enrolment_target * hc_nb
  enrolment_target <- round(day_target / facility_nb, 0)
} else if (Sys.getenv('TIMCI_COUNTRY') == "India") {
  hc_enrolment_target <- 22/6
  dispensary_enrolment_target <- 4/6
  day_target <- dispensary_enrolment_target * dispensary_nb + hc_enrolment_target * hc_nb
  enrolment_target <- ceiling(day_target / facility_nb)
} else{
  enrolment_target <- 8
}
```
