```{r}
write("o Export drug re-entry data and run corresponding quality checks", stderr())
```

\newpage

## Day 0 drug free text re-entry data quality checks

```{r}
db_name <- "Drug"
drug_is_not_null <- timci::is_not_empty(raw_drug_data)
n_raw_drug_records <- nrow(raw_drug_data)
```

There are **`r n_raw_drug_records`** record(s) in the raw `r db_name` database.

### Duplicated entries

```{r, results='asis', eval=drug_is_not_null}
qc_description <- "All participants should have a distinct ID. Duplicated IDs may generate errors for the conduct of follow-ups in the field and results in ambiguous outcomes for duplicated participants once the database is deidentified."
qc_rule <- "Remaining duplicated record IDs are deleted from the database."
qc_type <- "duplicates"
df <- raw_drug_data
col_id <- "uuid"
col_date <- "start"
cleaning <- "drop_all"
qc_text <- "duplicated IDs"
qc_idx <- qc_drug_duplicate_id
qc_export_label <- "timci_drug_data_id_duplicates"
qc_export_description <- "the submission was done twice for the same record ID"
cat(knitr::knit_child('database_export_sub_quality_check.Rmd',
                      envir = environment(),
                      quiet = TRUE))
```

```{r, eval=!is.null(cleaned_df)}
drug_data <- cleaned_df
```

### Data export

```{r}
write(" o Data export", stderr())
```

```{r, eval=drug_is_not_null, results = 'asis'}
timci::dataset_export(raw_drug_data,
                      "02z",
                      "timci_day0_drug_data",
                      rctls_dir,
                      "Raw Day 0 drug re-entry data")
```

```{r export-locked-drug-data, results = 'asis'}
timci::dataset_export(drug_data,
                      "02z",
                      "timci_day0_drug_data",
                      locked_db_dir,
                      "Cleaned Day 0 drug re-entry data")
```
