**Rule:** possible participant duplicates are detected based on their name, sex and date of birth. No specific action at the moment.

```{r check-RCT-LS-ODK-facility-data-002, results='asis'}
if (!is.null(facility_data)) {
  if (nrow(locked_pii) > 0) {
    day0_qc1 <- timci::detect_participant_duplicates(locked_pii)
    day0_qc <- merge(day0_qc, day0_qc1, by = 'child_id')
    duplicates <- day0_qc[(day0_qc$ex_name_fq > 1) | (day0_qc$sw_name_fq > 1),]
  }
}
```

```{r check-RCT-LS-ODK-facility-data-002-disp, results='asis'}
if (!is.null(facility_data)) {
  if (nrow(locked_pii) > 0) {
    if (length(duplicates) > 0 & nrow(duplicates) > 0) { 
      cat(paste0("", nrow(duplicates), " possible participant duplicates detected based on their name, sex and date of birth. No specific action was taken."))
    } else {
      cat("No duplicated names detected")
    }
  } else {
    cat("N/A")
  }
}
  
# Approximate String Matching (Fuzzy Matching)
#df <- dplyr::mutate(pii, full_name = tolower(paste(fs_name, ls_name, sep = ' ')))
#df3 <- df[c("child_id", "full_name")]
#qc3 <- lapply(list(df3$full_name), agrep, x = list(df3$full_name), value = TRUE)
#print(qc3)
```

```{r, results = 'asis', eval=(length(duplicates) > 0 & nrow(duplicates) > 0)}
duplicate_export_name <- "DQC_01_03_possible_multiple_enrolments"
ts <- timci::export_df2xlsx(duplicates,
                            qc_dir,
                            duplicate_export_name)
cat(paste0("* Possible multiple enrolment of the same children are exported (**", ts, "**) in ", duplicate_export_name, ".xslx in the ", qc_dir, " folder"))
```

#### Possible participant duplicates with sex discrepancy

**Rule:** possible participant duplicates detected based on their name and date of birth, but with a sex discrepancy. No specific action at the moment.

```{r, results='asis'}
if (!is.null(facility_data)) {
  if (nrow(locked_pii) > 0) {
    day0_qc2 <- timci::detect_namedob_duplicates(locked_pii)
    day0_qc <- merge(day0_qc, day0_qc2, by = 'child_id')
    duplicates2 <- day0_qc[(day0_qc$ex_name2_fq > 1 & day0_qc$ex_name2_fq > day0_qc$ex_name_fq) | (day0_qc$sw_name2_fq > 1 & day0_qc$sw_name2_fq > day0_qc$sw_name_fq),]
  }
}
```

```{r check-RCT-LS-ODK-facility-data-003-disp, results='asis'}
if (!is.null(facility_data)) {
  if (nrow(locked_pii) > 0) {
    if (length(duplicates2) > 0 & nrow(duplicates2) > 0) { 
      cat(paste0("", nrow(duplicates2), " possible participant duplicates detected based on their name and date of birth, but with sex discrepancy. No specific action was taken."))
    } else {
      cat("No possible participant duplicates detected based on their name and date of birth, but with sex discrepancy detected")
    }
  } else {
    cat("N/A")
  }
}
  
# Approximate String Matching (Fuzzy Matching)
#df <- dplyr::mutate(pii, full_name = tolower(paste(fs_name, ls_name, sep = ' ')))
#df3 <- df[c("child_id", "full_name")]
#qc3 <- lapply(list(df3$full_name), agrep, x = list(df3$full_name), value = TRUE)
#print(qc3)
```

```{r, results = 'asis', eval=(length(duplicates2) > 0 & nrow(duplicates2) > 0)}
duplicate2_export_name <- "DQC_01_03_possible_multiple_enrolments_with_sex_discrepancy"
ts <- timci::export_df2xlsx(duplicates2,
                            qc_dir,
                            duplicate2_export_name)
cat(paste0("* Possible multiple enrolment of the same children with sex discrepancy are exported (**", ts, "**) in ", duplicate2_export_name, ".xslx in the ", qc_dir, " folder"))
```

```{r export-duplicates}
if (!is.null(day0_qc)) {
  fn <- timci::export_df2xlsx(day0_qc,
                              qc_dir,
                              "07_data_quality_checks")
}
```
