```{r}
write("Export SPA sick child observation protocol data and run corresponding quality checks", stderr())
```

```{r}
locked_spa_sco_data <- spa_sco_data %>%
  dplyr::filter(date <= as.Date(lock_date, "%Y-%m-%d"))
n_raw_spa_sco_data <- nrow(locked_spa_sco_data)
spa_sco_db_name <- "SPA sick child observation"
```

There are **`r n_raw_spa_sco_data`** records between **`r spa_start_date`** and **`r lock_date`** in the raw `r spa_sco_db_name` database.

### Non-valid provider IDs\n\n

```{r, results='asis'}
out <- timci::correct_spa_sco_hcp_ids(locked_spa_sco_data)
locked_spa_sco_data <- out[[1]]
spa_sco_data_hcp_edits <- out[[2]]
spa_sco_data_hcp_edits %>%
  knitr::kable(caption = "Healthcare provider ID to be corrected")
```

### Non-valid participant IDs [compliance check `r qc_spa_sco_nonvalid_childid`]\n\n

```{r, eval=!is.null(locked_spa_sco_data), results='asis'}
qc_description <- ""
qc_rule <- "Keep only IDs of children who are enrolled in the locked Day 0 database."
qc_type <- "nonvalid_ids"
df <- locked_spa_sco_data
idcol1 <- "child_identification-pid"
refdf <- locked_day0_data
idcol2 <- "child_id"
qc_text <- "participant ID not valid"
db_name <- spa_sco_db_name
qc_idx <- qc_spa_sco_nonvalid_childid
qc_export_label <- "timci_spa_consultation_obs_data_unknown_ids"
qc_export_description <- "child IDs are not found in the Day 0 dataset"
cat(knitr::knit_child('database_export_sub_quality_check.Rmd',
                      envir = environment(),
                      quiet = TRUE))
```

```{r, eval=!is.null(cleaned_df)}
locked_spa_sco_data <- cleaned_df
```

### Duplicate management

**Rule:** keep duplicated records and investigate the reason for having duplicates.

```{r, results='asis'}
if (!is.null(spa_sco_data)) {
  if (length(spa_sco_data) > 0) {
    spa_sco_data_qc <- timci::detect_id_duplicates(locked_spa_sco_data %>% dplyr::rename(child_id = 'child_identification-pid'))
    spa_sco_data_duplicates <- spa_sco_data_qc[spa_sco_data_qc$id_fq > 1,]
    if (length(spa_sco_data_duplicates) > 0) {
      if (nrow(spa_sco_data_duplicates) > 0) {
         knitr::kable(spa_sco_data_duplicates, caption = "ID duplicates")
      }
    } else {
      cat("No ID duplicates detected")
    }
  }
}
```

```{r, results='asis'}
if (!is.null(spa_sco_data)) {
  if (length(spa_sco_data_duplicates) > 0) { 
    cat(paste0(nrow(spa_sco_data_duplicates), " duplicated IDs were detected. No action was taken in the locked SPA sick child observation database."))
  } else {
    cat(paste0("No duplicated IDs were detected. No action was taken in the locked SPA sick child observation database."))
  }
}
```

### Data cleaning summary

```{r, results = 'asis'}
if (!is.null(spa_sco_data)) {
  cat(paste0("There are ", nrow(locked_spa_sco_data), " records in the locked SPA sick child observation database."))
}
```

### Data export

```{r sick-child-observation-export, eval=deidentification_on}
spa_sco_data <- timci::deidentify_spa_data(spa_sco_data)
```

```{r, results='asis'}
timci::dataset_export(spa_sco_data,
                      "04",
                      "timci_spa_consultation_obs_data",
                      params$spa_dir,
                      "Raw SPA sick child observation data")
```

```{r, results='asis'}
timci::dataset_export(locked_spa_sco_data,
                      "04",
                      "timci_spa_consultation_obs_data",
                      locked_db_dir,
                      "Cleaned SPA sick child observation data")
```
