```{r}
write("Export Day 7 follow-up data and run corresponding quality checks", stderr())
```

## Day 7 follow-up data quality checks\n\n

```{r}
allday7fu_data <- NULL
day7fu_data <- NULL

locked_day7fu_data <- NULL
locked_allday7fu_data <- NULL
```

```{r format-RCT-LS-ODK-fu-day7-data}
db_name <- "Day 7 follow-up"
out <- timci::format_day7_data(raw_day7fu_data)
day7fu_data <- out[[1]]
allday7fu_data <- out[[3]]
```

There are **`r nrow(allday7fu_data)`** records in the raw `r db_name` database.

### Non-valid participant IDs [compliance check `r qc_nonvalid_day7fu`]\n\n

```{r}
write(" o Non-valid participant IDs [Day 7 data quality checks]", stderr())
```

```{r, eval=!is.null(allday7fu_data), results='asis'}
qc_description <- "Day 7 follow-ups are relevant only if associated to participants who were enrolled at Day 0."
qc_rule <- "Keep only IDs of children who can be found in the initial Day 0 database."
qc_type <- "nonvalid_ids"
df <- allday7fu_data
idcol1 <- "child_id"
refdf <- day0_data
idcol2 <- "child_id"
qc_text <- "non-valid participant IDs"
qc_idx <- qc_nonvalid_day7fu
qc_export_label <- "nonvalid_pids_day7fu"
qc_export_description <- "the child ID does not correspond to any ID found the locked Day 0 database"
cat(knitr::knit_child('database_export_sub_quality_check.Rmd',
                      envir = environment(),
                      quiet = TRUE))
```

```{r, eval=!is.null(cleaned_df)}
n_nonvalid_pids_day7fu <- n_detected
locked_day7fu_data <- cleaned_df
```

### Participants enrolled outside the lock date range [context check `r qc_pids_out_lock_range_day7fu`]\n\n

```{r, eval=!is.null(allday7fu_data), results='asis'}
qc_description <- paste0("Day 7 follow-ups are relevant only if associated to participants enrolled between the start date ", start_date, " and the lock date on ", lock_date, ".")
qc_rule <- "Discard follow-up records of participants who are enrolled in the Day 0 database outside the date range considered for the lock."
qc_type <- "nonvalid_ids"
df <- locked_day7fu_data
idcol1 <- "child_id"
refdf <- day0_data
idcol2 <- "child_id"
qc_text <- "participant IDs outside the lock date range"
qc_idx <- qc_pids_out_lock_range_day7fu
qc_export_label <- "pids_outside_lock_range"
qc_export_description <- "the follow-up correspond to a child who has been enrolled outside the date range for the lock"
cat(knitr::knit_child('database_export_sub_quality_check.Rmd',
                      envir = environment(),
                      quiet = TRUE))
```

```{r, eval=!is.null(cleaned_df)}
n_afterlock_pids_day7fu <- n_detected
locked_day7fu_data <- cleaned_df
```
