```{r}
write("Export service provision assessment (SPA) data and run corresponding quality checks", stderr())
```

```{r spa-conditions}
spa_sco_is_not_null <- is.null(spa_sco_data)
spa_sco_is_not_empty <- timci::is_not_empty(spa_sco_data)

spa_cgei_is_not_null <- !is.null(spa_cgei_data)
spa_cgei_is_not_empty <- timci::is_not_empty(spa_cgei_data)

spa_fa_is_not_null <- !is.null(spa_fa_data)
spa_fa_is_not_empty <- timci::is_not_empty(spa_fa_data)

spa_hcpi_is_not_null <- !is.null(spa_hcpi_data)
spa_hcpi_is_not_empty <- timci::is_not_empty(spa_hcpi_data)
```

## Sick child observation data quality checks

```{r, child = if(spa_sco_is_not_empty) 'database_export_sub_spa_sco.Rmd'}
```

## Healthcare provider interview data quality checks

```{r, child = if(spa_hcpi_is_not_empty) 'database_export_sub_spa_hcpi.Rmd'}
```

## Facility assessment data quality checks

```{r, child = if(spa_fa_is_not_empty) 'database_export_sub_spa_fa.Rmd'}
```

## Caregiver exit interview data quality checks

```{r, child = if(spa_cgei_is_not_empty) 'database_export_sub_spa_cgei.Rmd'}
```
