#### Child ID duplicates [compliance check] 

```{r, results='asis', eval=(is_tanzania | is_kenya)}
cat("Rule: child ID duplicates are detected and corrected proactively were possible.")
```

```{r, results='asis', eval=(is_tanzania | is_kenya)}
cat("##### Initial check")
```

```{r check-RCT-LS-ODK-facility-data-001a, results='asis'}
day0_qc <- NULL
if (!is.null(facility_data)) {
  if (nrow(locked_day0_data) > 0) {
    day0_qc <- timci::detect_id_duplicates(locked_day0_data)
    id_duplicates <- day0_qc[day0_qc$id_fq > 1,]
    if (nrow(id_duplicates) > 0) { 
      id_duplicates %>% knitr::kable(row.names = FALSE)
    }
  }
}
```

```{r, results='asis'}
day0_data_id_duplicates <- NULL
if (!is.null(facility_data)) {
  if (nrow(locked_day0_data) > 0) {
    if (nrow(id_duplicates) > 0) { 
      # Remove duplicate child IDs from the clean database
      day0_data_id_duplicates <- locked_day0_data[locked_day0_data$child_id %in% id_duplicates$child_id, ]
      cat(paste0("", nrow(id_duplicates), " duplicated IDs (corresponding to ", nrow(day0_data_id_duplicates), " participants) were detected in the locked Day 0 database."))
    } else {
      cat("No duplicated IDs were detected.")
    }
  } else {
    cat("N/A")
  }
}
```

```{r, results='asis'}
cat("##### Child ID duplicate manual edits")
```

```{r, results='asis'}
out <- timci::correct_day0_duplicates(locked_day0_data)
locked_day0_data <- out[[1]]
duplicate_edits <- out[[2]]
if (!is.null(duplicate_edits)) {
  duplicate_edits %>%
    select(old_child_id, uuid, new_child_id) %>%
    knitr::kable()
}
```

```{r, results='asis'}
cat("##### Second check after manual edits")
```

Rule: remaining child ID duplicates are removed in the locked database.

```{r check-RCT-LS-ODK-facility-data-001, results='asis'}
day0_qc <- NULL
if (!is.null(facility_data)) {
  if (nrow(locked_day0_data) > 0) {
    day0_qc <- timci::detect_id_duplicates(locked_day0_data)
    id_duplicates <- day0_qc[day0_qc$id_fq > 1,]
    if (nrow(id_duplicates) > 0) { 
      id_duplicates %>% knitr::kable(row.names = FALSE)
    }
  }
}
```

```{r, results='asis'}
day0_data_id_duplicates <- NULL
if (!is.null(facility_data)) {
  if (nrow(locked_day0_data) > 0) {
    if (nrow(id_duplicates) > 0) { 
      # Remove duplicate child IDs from the clean database
      day0_data_id_duplicates <- locked_day0_data[locked_day0_data$child_id %in% id_duplicates$child_id, ]
      locked_day0_data <- locked_day0_data[!locked_day0_data$child_id %in% id_duplicates$child_id, ]
      cat(paste0("", nrow(id_duplicates), " duplicated IDs (corresponding to ", nrow(day0_data_id_duplicates), " participants) were detected and removed in the locked Day 0 database."))
    } else {
      cat("No duplicated IDs were detected.")
    }
  } else {
    cat("N/A")
  }
}
```
