```{r}
write("Export Day 28 data and run corresponding quality checks", stderr())
```

\newpage

## Day 28 data quality checks

```{r format-RCT-LS-ODK-fu-day28-data}
day28fu_data <- NULL
allday28fu_data <- NULL
if (!is.null(raw_day28fu_data)) {
  if (nrow(raw_day28fu_data) > 0) {
    res <- timci::format_day28_data(raw_day28fu_data)
    day28fu_data <- res[[1]]
    allday28fu_data <- res[[3]]
  }
}
```

```{r, results = 'asis'}
if (!is.null(allday28fu_data)) {
  cat(paste0("There are **", nrow(allday28fu_data), "** records in the raw Day 28 follow-up database, among which **", nrow(day28fu_data), "** records documenting successful follow-ups."))
}
```

### Non-valid participant IDs

**Rule:** keep only IDs of children who are enrolled in the locked Day 0 database.

```{r}
locked_day28fu_data <- NULL
locked_allday28fu_data <- NULL
allday28fu_data_uids <- NULL
day28fu_data_uids <- NULL
if (!is.null(day28fu_data)) {
  # All follow-ups
  locked_allday28fu_data <- allday28fu_data[allday28fu_data$child_id %in% locked_day0_data$child_id, ]
  allday28fu_data_uids <- allday28fu_data[!allday28fu_data$child_id %in% locked_day0_data$child_id, ]
  # Successful follow-ups
  locked_day28fu_data <- day28fu_data[day28fu_data$child_id %in% locked_day0_data$child_id, ]
  day28fu_data_uids <- day28fu_data[!day28fu_data$child_id %in% locked_day0_data$child_id, ]
  locked_day28fu_data <- locked_day28fu_data %>% 
    dplyr::mutate(window = ifelse(days >= 28 & days <= 32, 1, 0))
}
```

```{r, results='asis'}
timci::format_nrow("", allday28fu_data_uids, "records with non-valid participant IDs were detected and removed in the locked Day 28 follow-up database.")
```

```{r, results='asis'}
timci::format_nrow("", day28fu_data_uids, "records with non-valid participant IDs were detected and removed in the locked successful Day 28 follow-up database.")
```

```{r, results = 'asis'}
timci::quality_check_export(allday28fu_data_uids[c("child_id", "uuid")],
                            qc_nonvalid_day28fu,
                            "nonvalid_ids_day28fu",
                            qc_dir,
                            "the child ID does not correspond to any ID found the locked Day 0 database")
```

### Duplicate management

**Rule:** only one successful follow-up is kept with the following priority rule: day 28 > day 29 > day 30 > day 31 > day 32 > day 27 > day 33 > day 34 > day 35 and above.

```{r check-RCT-LS-ODK-fu-day28-data, results='asis'}
day28fu_duplicates <- NULL
if (!is.null(locked_day28fu_data)) {
  day28fu_qc <- timci::detect_id_duplicates(locked_day28fu_data)
  day28fu_duplicates <- day28fu_qc[day28fu_qc$id_fq > 1,]
  if (length(day28fu_duplicates) > 0) { 
       knitr::kable(day28fu_duplicates,
                    caption = "ID duplicates",
                    row.names = FALSE)
  } else {
    cat("No ID duplicates detected")
  }
}
```

```{r}
day28fu_data_duplicates <- NULL
if (!is.null(day28fu_data)) {
  # Process duplicates separately
  day28fu_data_duplicates <- locked_day28fu_data[locked_day28fu_data$child_id %in% day28fu_duplicates$child_id, ]
  processed_day28fu_data_duplicates <- day28fu_data_duplicates %>%
    dplyr::group_by(child_id) %>%
    dplyr::slice_max(order_by = window) %>%
    dplyr::slice_min(order_by = days)
  # Remove all duplicates from the list and concatenate with the filtered list
  locked_day28fu_data <- locked_day28fu_data[!locked_day28fu_data$child_id %in% day28fu_duplicates$child_id, ]
  locked_day28fu_data <- rbind(locked_day28fu_data, processed_day28fu_data_duplicates)
}
```

```{r, results = 'asis'}
if (!is.null(day28fu_data_duplicates)) {
  n <- nrow(day28fu_data_duplicates) - nrow(processed_day28fu_data_duplicates)
  if (n > 1) {
    cat(paste0("**", n, "** records were removed in the locked successful Day 28 follow-up database (records duplicated on the same day may be kept - we need to define a rule for this)."))
  } else if (n == 1) {
    cat("**1** record was removed in the locked successful Day 28 follow-up database (records duplicated on the same day may be kept - we need to define a rule for this).")
  } else{
    cat(paste0("No records were removed in the locked successful Day 28 follow-up database."))
  }
}
```

### Data cleaning summary

```{r, results = 'asis'}
if (!is.null(locked_day28fu_data)) {
  cat(paste0("There are **", nrow(locked_day28fu_data), "** records in the locked Day 28 follow-up database."))
} else{
  cat("N/A")
}
```

```{r}
timci::create_flowchart(nrow(allday28fu_data),
                        nrow(locked_day28fu_data),
                        'NA',
                        'NA',
                        'NA',
                        'NA',
                        'NA')
```

### Data export

```{r, results = 'asis'}
timci::dataset_export(allday28fu_data,
                      "06a",
                      "timci_followup_day28_data",
                      rctls_dir,
                      "Raw Day 28 follow-up data")
```

```{r, results = 'asis'}
timci::dataset_export(day28fu_data,
                      "06b",
                      "timci_followup_successful_day28_data",
                      rctls_dir,
                      "Raw successful Day 28 follow-up only)")
```

```{r, results = 'asis'}
timci::dataset_export(locked_allday28fu_data,
                      "06a",
                      "timci_followup_day28_data",
                      locked_db_dir,
                      "Cleaned Day 28 follow-up data")
```

```{r, results = 'asis'}
timci::dataset_export(locked_day28fu_data,
                      "06b",
                      "timci_followup_successful_day28_data",
                      locked_db_dir,
                      "Cleaned successful Day 28 follow-up data")
```

```{r, results = 'asis'}
fu28all <- NULL
if (!is.null(pii) & !is.null(raw_day28fu_data)) {
  fu28all <- timci::generate_fu_log(pii,
                                    raw_day28fu_data,
                                    0,
                                    32,
                                    28,
                                    32,
                                    ext = TRUE,
                                    deidentify = TRUE)
}
```

```{r, results = 'asis'}
timci::dataset_export(fu28all,
                      "06d",
                      "timci_day28_fu_weekly_log_all",
                      rctls_dir,
                      "Weekly Day 28 follow-up data")
```
