---
title: "Untitled"
author: "H. LANGET"
date: "14 9 2021"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r, results = "asis", fig.height = 3}
cfid <- facilities[[i, 'facility_id']]
fname <- facilities[[i, 'facility_name']]
ftype <- facilities[[i, 'type']]

noneligible_tmp <- noneligible %>% dplyr::filter(fid == cfid)
baseline_data_tmp <- baseline_data %>% dplyr::filter(fid == cfid)
repeat_data_tmp <- repeat_data %>% dplyr::filter(fid == cfid)
```

## `r fname`

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("### Recrutement hebdomadaire\n\n")
} else {
  cat("### Weekly enrolment\n\n")
}
```

```{r, results = "asis", fig.height = 3}
if (!is.null(baseline_data_tmp) & length(baseline_data_tmp) > 0 & nrow(baseline_data_tmp) > 0) {
  if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania") {
    if (ftype == "dispensary") {
      val <- 5 * dispensary_enrolment_target
    } else{
      val <- 5 * hc_enrolment_target
    }
  } else{
    val <- 5 * enrolment_target
  }
  p <- timci::generate_week_bar_plot(date_vec = baseline_data_tmp$date_visit,
                                     date_min = as.Date(start_date),
                                     date_max = as.Date(Sys.Date() + 1),
                                     ylbl = paste0(enrolment_str),
                                     rref = val,
                                     relative = FALSE)
  plot(p)
}
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("### Recrutement quotidien\n\n")
} else {
  cat("### Daily enrolment\n\n")
}
```

```{r, results = "asis", fig.height = 3}
w <- 30

if (!is.null(baseline_data_tmp) & length(baseline_data_tmp) > 0 & nrow(baseline_data_tmp) > 0) {
  if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania") {
    if (ftype == "dispensary") {
      val <- dispensary_enrolment_target
    } else{
      val <- hc_enrolment_target
    }
  } else{
    val <- enrolment_target
  }
  p <- timci::generate_day_bar_plot(date_vec = baseline_data_tmp$date_visit,
                                    date_min = as.Date(Sys.Date() - w),
                                    date_max = as.Date(Sys.Date() + 1),
                                    ylbl = paste0(enrolment_str),
                                    rref = val)
  plot(p)
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("### Cartes thermiques calendaires\n\n")
} else {
  cat("### Calendar heatmaps\n\n")
}

if (!is.null(baseline_data_tmp) & length(baseline_data_tmp) > 0 & nrow(baseline_data_tmp) > 0) {
  timci::generate_calendar_heatmap(baseline_data_tmp, date_visit)
}
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("### Heures de screening\n\n")
} else {
  cat("### Screening times\n\n")
}
```

```{r, results = "asis", fig.height = 3}
facility_data_tmp <- facility_data %>% dplyr::filter(fid == cfid)
if (!is.null(facility_data_tmp) & length(facility_data_tmp) > 0 & nrow(facility_data_tmp) > 0) {
  timci::generate_time_hist_plot(facility_data_tmp, screening_times_str)
}
```
