---
title: "Untitled"
author: "H. LANGET"
date: "14 9 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r, results = "asis"}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Soumissions par poste de santé\n\n")
} else {
  cat("## Submissions by facility\n\n")
}
```

```{r fig.height=8, results='asis'}
if (nrow(facility_data) > 0) {
  stats <- timci::get_summary_by_deviceid(facility_data)
  stats <- merge(x = stats, y = params$research_facilities, by.x = 'device_id', by.y = 'deviceid', all.x = TRUE)
  stats$screened <- stats$screened / days_nb
  stats$children <- stats$children / days_nb
}

if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania') {
  min_target_day <- 5
  max_target_day <- 8
} else {
  min_target_day <- 0.6 * enrolment_target
  max_target_day <- enrolment_target
}
```

```{r fig.height=8, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("### Moyenne quotidienne de recrutements par poste de santé\n\n"))
} else {
  cat(paste0("### Enrolment daily average by facility\n\n"))
}
timci::generate_enrolment_hist(stats, facility_label, children, min_target_day, max_target_day, "Daily average of children enrolled", "facilities")
```

```{r fig.height=8, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("### Moyenne quotidienne de screenings par poste de santé\n\n"))
} else {
  cat(paste0("### Screening daily average by facility\n\n"))
}
timci::generate_enrolment_hist(stats, facility_label, screened, min_target_day+1, max_target_day, "Daily average of children screened", "facilities")
```

```{r, results = "asis"}
w <- 30
for (i in 1:nrow(facilities)) {
  cfid <- facilities[[i, 'facility_id']]
  fname <- facilities[[i, 'facility_name']]
  ftype <- facilities[[i, 'type']]
  baseline_data_tmp <- baseline_data %>% dplyr::filter(fid == cfid)
  if (!is.null(baseline_data_tmp) & length(baseline_data_tmp) > 0 & nrow(baseline_data_tmp) > 0) {
    if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania") {
      if (ftype == "dispensary") {
        val <- dispensary_enrolment_target
      } else{
        val <- hc_enrolment_target
      }
    } else{
      val <- enrolment_target
    }
    p <- timci::generate_day_bar_plot(date_vec = baseline_data_tmp$date_visit,
                                      date_min = as.Date(Sys.Date() - w),
                                      date_max = as.Date(Sys.Date() + 1),
                                      ylbl = paste0(enrolment_rate_str),
                                      rref = val)
    p <- p + ggplot2::ggtitle(fname)
    plot(p)
  }
}
```

```{r fig.height=8, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("### Moyenne quotidienne d'appels téléphoniques à jour 7 par poste de santé\n\n"))
  cat(paste0("A compléter\n\n"))
} else {
  cat(paste0("### Day 7 phone calls by facility\n\n"))
  cat(paste0("To be completed\n\n"))
}
#timci::generate_enrolment_hist(stats, facility_label, children, 5, 15, "Number of children enrolled", "facilities")
```
