---
title: "TIMCI `r if(Sys.getenv('TIMCI_IS_RCT') == 1){'Pragmatic cluster RCT'} else{'Longitudinal Observational Study'}` - Pilot Report"
author: "`r if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania') {'Ifakara Health Institute (IHI)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'India') {'King George s Medical University (KGMU)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {'Université Cheikh Anta Diop de Dakar (UCAD)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Kenya') {'University of Nairobi (UoN)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Myanmar') {'Burnet Institute (BI)'} else {'Swiss Tropical and Public Health Institute (Swiss TPH)'}`"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document: default
  word_document:
    reference_docx: word_styles1.docx
    fig_width: 7.5
---

```{r setup-rmd, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup-ruODK, echo=FALSE}
ruODK::ru_setup(
  svc = Sys.getenv("ODKC_SVC"),
  un = Sys.getenv("ODKC_UN"),
  pw = Sys.getenv("ODKC_PW"),
  tz = Sys.getenv("TZ"),
  verbose = FALSE # Can be switched to TRUE for demo or debugging
)
```

```{r, echo=FALSE}
crf_facility_fid <- Sys.getenv("TIMCI_CRF_FACILITY_FID")
crf_day7_fid <- Sys.getenv("TIMCI_CRF_DAY7_FID")
crf_hospit_fid <- Sys.getenv("TIMCI_CRF_HOSPIT_FID")
if (Sys.getenv('TIMCI_IS_RCT') == 1) {
  crf_day28_fid <- Sys.getenv("TIMCI_CRF_DAY28_FID")
}
wd_fid <- Sys.getenv("TIMCI_WD_FID")
form_list <- ruODK::form_list()$fid
```

```{r, echo=FALSE}
raw_facility_data <- ruODK::odata_submission_get(fid = crf_facility_fid,
                                                 download = FALSE)
raw_day7fu_data <- NULL
if (crf_day7_fid %in% form_list) {
  raw_day7fu_data <- ruODK::odata_submission_get(fid = crf_day7_fid,
                                                 download = FALSE)
}
raw_hospit_data <- NULL
if (crf_hospit_fid %in% form_list) {
raw_hospit_data <- ruODK::odata_submission_get(fid = crf_hospit_fid,
                                               download = FALSE)
}

if (Sys.getenv('TIMCI_IS_RCT') == 1) {
  raw_day28fu_data <- NULL
  if (crf_day28_fid %in% form_list) {
    raw_day28fu_data <- ruODK::odata_submission_get(fid = crf_day28_fid,
                                                  download = FALSE)
  }
}

raw_withdrawal_data <- NULL
if (wd_fid %in% form_list) {
raw_withdrawal_data <- ruODK::odata_submission_get(fid = wd_fid,
                                                   download = FALSE)
}
```

```{r process-facility-data, echo=FALSE, warning=FALSE}
facility_data <- NULL
start_date <- NULL
end_date <- NULL
if (nrow(raw_facility_data) > 0) {
  facility_data <- timci::process_facility_data(raw_facility_data)
  start_date <- min(facility_data$date_visit)
  end_date <- max(facility_data$date_visit)
}
```

This report covers the period from **`r start_date`** to **`r end_date`**.

# 1. Submissions

## Total number of submissions per form
```{r submissions-1, echo=FALSE, results = "asis"}

n_total <-0

# Screening data
n_screened <- nrow(facility_data)
screening_data <- timci::extract_screening_data(facility_data)
visit_names <- c("Screening")
submissions <- c(n_screened)
n_total <- n_total + n_screened

study_data <- timci::extract_all_visits(facility_data)
res <- timci::extract_enrolled_participants(facility_data)

# Baseline data
baseline_data <- timci::extract_baseline_visits(study_data)
demog_data <- res[[1]]
n_enrolled <- nrow(demog_data)
visit_names <- c(visit_names, "Baseline visit")
submissions <- c(submissions, n_enrolled)

# Count facility submissions corresponding to repeat visits
repeat_data <- timci::extract_repeat_visits(study_data)
n_repeat <- nrow(repeat_data)
visit_names <- c(visit_names, "Repeat visit")
submissions <- c(submissions, n_repeat)

# Count Day 7 phone call submissions
if (!is.null(raw_day7fu_data)) {
  n_day7fu <- nrow(raw_day7fu_data)
  visit_names <- c(visit_names, "Day 7 phone call")
  submissions <- c(submissions, n_day7fu)
  n_total <- n_total + n_day7fu
}

# Count hospital visit submissions
if (!is.null(raw_hospit_data)) {
  n_hospit <- nrow(raw_hospit_data)
  visit_names <- c(visit_names, "Hospital visit")
  submissions <- c(submissions, n_hospit)
  n_total <- n_total + n_hospit
}

# Count withdrawal submissions
if (!is.null(raw_withdrawal_data)) {
  n_withdrawal <- nrow(raw_withdrawal_data)
  visit_names <- c(visit_names, "Withdrawal")
  submissions <- c(submissions, n_withdrawal)
  n_total <- n_total + n_withdrawal
}

if (Sys.getenv('TIMCI_IS_RCT') == 1) {
  if (!is.null(raw_day28fu_data)) {
    n_day28fu <- nrow(raw_day28fu_data)
    visit_names <- c(visit_names, "Day 28 phone call")
    submissions <- c(submissions, n_day28fu)
    n_total <- n_total + n_day28fu
  }
}
  
visit_names <- c(visit_names, "All")
submissions <- c(submissions, n_total)

visits <- data.frame(visit_names, submissions) 
knitr::kable(visits, col.names = c("Visit", "N"))
```
