---
title: "TIMCI `r if (Sys.getenv('TIMCI_COUNTRY') != 'Senegal') {'Process Mapping & Time-flow - Monitoring Report'} else {'Cartographie des processus & flux temporel - Rapport de suivi'}`"
author: "`r if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania') {'Ifakara Health Institute (IHI)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'India') {'King George s Medical University (KGMU)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {'Université Cheikh Anta Diop de Dakar (UCAD)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Kenya') {'University of Nairobi (UoN)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Myanmar') {'Burnet Institute (BI)'} else {'Swiss Tropical and Public Health Institute (Swiss TPH)'}`"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M')`"
params:
  research_facilities: !r data.frame(deviceid = character(0), district = character(0), facility = character(0))
  facility_data: NULL
  tf_data: NULL
  pm_data: NULL
  raw_withdrawal_data: NULL
output:
  word_document:
    reference_docx: word_styles1.docx
    fig_width: 7.5
  html_document:
    number_sections: true
  pdf_document:
    number_sections: true
    toc: true
    toc_depth: 3
    extra_dependencies: ["float", "flafter", "bm"]
---

```{r setup-rmd, include=FALSE}
library(magrittr)
library(readxl)
library(ggplot2)
library(lubridate)
library(gridExtra)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.pos='!H')
options(qwraps2_markup = 'markdown')

# Qwraps2 parameters
prec <- 1

#kableExtra table parameters
table_fs <- 7
figsize <- 3
total_row_ft <- "gray"
total_row_ft2 <- "white"
striped_row_bg <- "gray!10"
total_row_bg2 <- "gray"
```

```{r translations}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  notice_str <- "\\begin{center}\\textbf{Pour usage interne uniquement. Ne pas partager en dehors des équipes recherche. Les tableaux et les figures sont générés à partir des bases de données brutes, et non à partir des bases de données nettoyées, et les résultats de ce rapport peuvent donc être légèrement différents de ceux de l'analyse statistique formelle.}\\end{center}"
  intro_str <- "L’objectif global du projet TIMCI (Outils pour la prise en charge intégrée des maladies de l’enfant) est de réduire la morbidité et la mortalité chez les enfants malades dans les structures de soins primaires, tout en soutenant l’utilisation rationnelle et efficace des moyens diagnostiques et des médicaments par les prestataires de soins de santé. Le volet évaluation du projet vise à apporter des preuves de l’impact de l’introduction de l’oxymètre de pouls, associé à un Algorithme d’aide à la décision clinique (CDSA), sur la santé, les priorités opérationnelles, le coût et l’analyse cout-efficacité modélisée dans le contexte des soins primaires, pour les enfants âgés de 0 à 59 mois des pays à revenu faible ou intermédiaire (PRFI), en vue de faciliter la prise de décision et la mise à l’échelle aux niveaux national et international."
  baseline_str <- "Visite primaire"
  facility_cap <- "Liste des poste de recherche"
  repeat_str <- "Visite secondaire"
  submission_str <- "Soumissions"
  enrolment_rate_str <- "Taux de recrutement par rapport à l'objectif"
  enrolment_str <- "Recrutement"
  screening_str <- "Screening"
  withdrawal_str <- "Désistement"
  pm_h1 <- "# Cartographie des processus\n\n"
  screening_times_str <- "Heures de screening"
  tf_h1 <- "# Flux temporels\n\n"
} else {
  notice_str <- "\\begin{center}\\textbf{For internal use only. Do not share outside research teams. Tables and figures are generated from raw databases, not from the cleaned databases, and findings of this report can therefore be slightly different from those of the formal statistical analysis.}\\end{center}"
  intro_str <- "The overall goal of the Tools for the Management of Childhood Illness (TIMCI) project is to reduce morbidity and mortality in sick children attending primary care facilities, while supporting the rational and efficient use of diagnostics and medicines by healthcare providers. The evaluation component of the project seeks to generate evidence on the health impact, operational priorities, cost and cost-effectiveness of introducing pulse oximetry, alone or embedded into a Clinical Decision Support Algorithm (CDSA), at primary care level in LMICs, for children 0 – 59 months of age, to facilitate national and international decision-making on scale-up."
  baseline_str <- "Baseline visit"
  facility_cap <- "List of research facilities"
  repeat_str <- "Repeat visit"
  submission_str <- "Submissions"
  enrolment_rate_str <- "Enrolment rate vs. target"
  enrolment_str <- "Enrolment"
  screening_str <- "Screening"
  withdrawal_str <- "Withdrawal"
  pm_h1 <- "# Process mapping\n\n"
  screening_times_str <- "Screening times"
  tf_h1 <- "# Time-flow\n\n"
}
```

\newpage

```{r notice-text, results='asis'}
cat(notice_str)
```

```{r introduction-text, results='asis'}
cat(intro_str)
```

```{r setup-variables}
if (!is.null(params$facility_data)) {
  
  facility_data <- params$facility_data
  tf_data <- params$tf_data
  pm_data <- params$pm_data
  raw_withdrawal_data <- params$raw_withdrawal_data
  
}

# Extract personally identifiable data
pii <- timci::extract_enrolled_participants(facility_data)[[2]]

# Merge facility generic info with facility data
facility_data <- merge(facility_data, params$research_facilities[, c("deviceid", "facility_name")], by.x = 'device_id', by.y = 'deviceid', all.x = TRUE)
```

```{r process-facility-data, results='asis'}
start_date <- NULL
end_date <- NULL
if (nrow(tf_data) > 0) {
  start_date <- min(tf_data$date)
  end_date <- max(tf_data$date)
  week_nb <- ceiling(difftime(as.Date(end_date), as.Date(start_date) - 1,units = "weeks"))
  days_nb <- sum(!lubridate::wday(seq(as.Date(start_date), as.Date(end_date), "days")) %in% c("7", "1"))
  if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
    cat(paste0("Ce rapport couvre la période du **", start_date, "** (début de l'étude) au **", end_date, "** pour le **Sénégal**."))
  } else {
    cat(paste0("This report covers the period from **", start_date, "** (study start) to **", end_date, "** for **", Sys.getenv('TIMCI_COUNTRY'), "**."))
  }
}
```

```{r context-title, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  title_str <- "# Contexte\n\n"
} else {
  title_str <- "# Context\n\n"
}
cat(title_str)
```

```{r context-load-facilities, results='asis'}
facilities <- params$research_facilities %>% filter(spa == 1)
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  facilities <- facilities[, c("lvl2", "facility_id", "facility_name")]
  facilities <- facilities[!duplicated(facilities$facility_id), ]
} else{
  facilities <- facilities[, c("lvl2", "facility_id", "facility_name", "type")]
  facilities <- facilities[!duplicated(facilities$facility_id), ]
}
```

```{r context-display-facilities, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  # Sort by district and rename columns
  facility_disp <- facilities %>%
    dplyr::arrange(lvl2) %>%
    dplyr::rename('District sanitaire' = 'lvl2',
                  'ID' = 'facility_id',
                  'Poste de santé' = 'facility_name')
} else if(Sys.getenv('TIMCI_COUNTRY') == 'Kenya'){
  # Sort by County then type of facility
  facility_disp <- facilities %>%
    dplyr::arrange(lvl2, type) %>%
    dplyr::rename('County' = 'lvl2',
                  'ID' = 'facility_id',
                  'Facility' = 'facility_name',
                  'Type' = 'type')
  
} else{
  # Sort by district then type of facility
  facility_disp <- facilities %>%
    dplyr::arrange(lvl2, type) %>%
    dplyr::rename('District' = 'lvl2',
                  'ID' = 'facility_id',
                  'Facility' = 'facility_name',
                  'Type' = 'type')
  
}
facility_nb <- nrow(facilities)
if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania' | Sys.getenv('TIMCI_COUNTRY') == 'Kenya') {
  facilities$type <- tolower(facilities$type)
  hc_nb <- nrow(facilities %>% filter(type == "health center"))
  dispensary_nb <- nrow(facilities %>% filter(type == "dispensary"))
  cat(paste0(facility_nb, " research facilities, among which ", hc_nb, " health centres and ", dispensary_nb, " dispensaries"))
} else{
  cat(paste0(facility_nb, " research facilities"))
}
```

```{r context-facilities, results = "asis"}
facility_disp  %>% 
  kableExtra::kbl(booktabs = TRUE,
                  linesep = "",
                  caption = facility_cap,
                  align = c("c", "c", "c")) %>% 
  kableExtra::kable_styling(latex_options = c("HOLD_position", "repeat_header"),
                            font_size = table_fs) %>%
  kableExtra::row_spec(0, color = total_row_ft2, background = total_row_bg2, bold = TRUE) %>%
  kableExtra::collapse_rows(columns = 1, valign = "top") 
```

\newpage

```{r pm-h1, results='asis'}
cat(pm_h1)
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Cartes thermiques calendaires\n\n")
} else {
  cat("## Calendar heatmaps\n\n")
}

if (!is.null(pm_data)){
  if (nrow(pm_data) > 0) {
    timci::generate_calendar_heatmap2(pm_data,
                                      date,
                                      legendtitle = "Number of submissions")
  }
}
```

\newpage

```{r tf-h1, results='asis'}
cat(tf_h1)
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Cartes thermiques calendaires\n\n")
} else {
  cat("## Calendar heatmaps\n\n")
}

if (!is.null(tf_data)){
  if (nrow(tf_data) > 0) {
    timci::generate_calendar_heatmap2(tf_data,
                                      date,
                                      legendtitle = "Number of submissions")
  }
}
```
