---
title: "TIMCI `r if (Sys.getenv('TIMCI_COUNTRY') != 'Senegal') {'Qualitative studies - Monitoring Report'} else {'Etude qualitatives - Rapport de suivi'}`"
author: "`r if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania') {'Ifakara Health Institute (IHI)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'India') {'King George s Medical University (KGMU)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {'Université Cheikh Anta Diop de Dakar (UCAD)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Kenya') {'University of Nairobi (UoN)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Myanmar') {'Burnet Institute (BI)'} else {'Swiss Tropical and Public Health Institute (Swiss TPH)'}`"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M')`"
params:
  research_facilities: !r data.frame(deviceid = character(0), district = character(0), facility = character(0))
  facility_data: NULL
  hcpidi_interview_data: NULL
  raw_withdrawal_data: NULL
output:
  word_document:
    reference_docx: word_styles1.docx
    fig_width: 7.5
  html_document:
    number_sections: true
  pdf_document:
    number_sections: true
    toc: true
    toc_depth: 3
    extra_dependencies: ["float", "flafter", "bm"]
---

```{r setup-rmd, include=FALSE}
library(magrittr)
library(readxl)
library(ggplot2)
library(lubridate)
library(gridExtra)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.pos='!H')
options(qwraps2_markup = 'markdown')

# Qwraps2 parameters
prec <- 1

#kableExtra table parameters
table_fs <- 7
figsize <- 3
total_row_ft <- "gray"
total_row_ft2 <- "white"
striped_row_bg <- "gray!10"
total_row_bg2 <- "gray"
```

```{r translations-subsection, child = 'translations.Rmd'}
```

\newpage

`r notice_str`

`r intro_str`

```{r setup-variables}
if (!is.null(params$facility_data)) {
  
  facility_data <- params$facility_data
  hcpidi_interview_data <- params$hcpidi_interview_data
  raw_withdrawal_data <- params$raw_withdrawal_data
  
}

# Extract personally identifiable data
pii <- timci::extract_enrolled_participants(facility_data)[[2]]

# Merge facility generic info with facility data
facility_data <- merge(facility_data, params$research_facilities[, c("deviceid", "facility_name")], by.x = 'device_id', by.y = 'deviceid', all.x = TRUE)
```

```{r process-facility-data, results='asis'}
start_date <- NULL
end_date <- NULL
if (nrow(hcpidi_interview_data) > 0) {
  start_date <- min(hcpidi_interview_data$date)
  end_date <- max(hcpidi_interview_data$date)
  week_nb <- ceiling(difftime(as.Date(end_date), as.Date(start_date) - 1,units = "weeks"))
  days_nb <- sum(!lubridate::wday(seq(as.Date(start_date), as.Date(end_date), "days")) %in% c("7", "1"))
  if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
    cat(paste0("Ce rapport couvre la période du **", start_date, "** (début de l'étude) au **", end_date, "** pour le **Sénégal**."))
  } else {
    cat(paste0("This report covers the period from **", start_date, "** (study start) to **", end_date, "** for **", Sys.getenv('TIMCI_COUNTRY'), "**."))
  }
}
```

```{r context-subsection, child = 'context.Rmd'}
```

```{r hcpidi-subsection, child = if (!is.null(hcpidi_interview_data)) 'qual_monitoring_report_sub_hcpidi.Rmd'}
```

\newpage
\listoftables

\newpage
\listoffigures

```{r technical-info-subsection, child = 'technical_info.Rmd'}
```
