---
title: "TIMCI `r if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania' || Sys.getenv('TIMCI_COUNTRY') == 'India') {'Pragmatic cluster RCT - Monitoring Report'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {'Étude Longitudinale Observationnelle - Rapport de suivi'} else {'Longitudinal Observational Study (LS) - Monitoring Report'}`"
author: "`r if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania') {'Ifakara Health Institute (IHI)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'India') {'King George s Medical University (KGMU)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {'Université Cheikh Anta Diop de Dakar (UCAD)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Kenya') {'University of Nairobi (UoN)'} else if (Sys.getenv('TIMCI_COUNTRY') == 'Myanmar') {'Burnet Institute (BI)'} else {'Swiss Tropical and Public Health Institute (Swiss TPH)'}`"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M')`"
params:
  research_facilities: !r data.frame(deviceid = character(0), district = character(0), facility = character(0))
  facility_data: NULL
  raw_day7fu_data: NULL
  raw_hospit_data: NULL
  raw_day28fu_data: NULL
  raw_withdrawal_data: NULL
  wfa_data: NULL
output:
  word_document:
    reference_docx: word_styles1.docx
    fig_width: 7.5
  html_document:
    number_sections: true
  pdf_document:
    number_sections: true
    toc: true
    toc_depth: 3
---

```{r setup-rmd, include=FALSE}
library(magrittr)
library(readxl)
library(ggplot2)
library(lubridate)
library(gridExtra)
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
options(qwraps2_markup = 'markdown')
pres <- 1
```

```{r translations}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  notice_str <- "\\begin{center}\\textbf{Pour usage interne uniquement. Ne pas partager en dehors des équipes recherche. Les tableaux et les figures sont générés à partir des bases de données brutes, et non à partir des bases de données nettoyées, et les résultats de ce rapport peuvent donc être légèrement différents de ceux de l'analyse statistique formelle.}\\end{center}"
  intro_str <- "L’objectif global du projet TIMCI (Outils pour la prise en charge intégrée des maladies de l’enfant) est de réduire la morbidité et la mortalité chez les enfants malades dans les structures de soins primaires, tout en soutenant l’utilisation rationnelle et efficace des moyens diagnostiques et des médicaments par les prestataires de soins de santé. Le volet évaluation du projet vise à apporter des preuves de l’impact de l’introduction de l’oxymètre de pouls, associé à un Algorithme d’aide à la décision clinique (CDSA), sur la santé, les priorités opérationnelles, le coût et l’analyse cout-efficacité modélisée dans le contexte des soins primaires, pour les enfants âgés de 0 à 59 mois des pays à revenu faible ou intermédiaire (PRFI), en vue de faciliter la prise de décision et la mise à l’échelle aux niveaux national et international."
  context_title_str <- "# Contexte\n\n"
  baseline_str <- "Visite primaire"
  repeat_str <- "Visite secondaire"
  submission_str <- "Soumissions"
  enrolment_rate_str <- "Taux de recrutement par rapport à l'objectif"
  enrolment_str <- "Recrutement"
  screening_str <- "Screening"
  withdrawal_str <- "Désistement"
  appendix_title <- "# Annexe\n\n"
  screening_times_str <- "Heures de screening"
} else {
  notice_str <- "\\begin{center}\\textbf{For internal use only. Do not share outside research teams. Tables and figures are generated from raw databases, not from the cleaned databases, and findings of this report can therefore be slightly different from those of the formal statistical analysis.}\\end{center}"
  intro_str <- "The overall goal of the Tools for the Management of Childhood Illness (TIMCI) project is to reduce morbidity and mortality in sick children attending primary care facilities, while supporting the rational and efficient use of diagnostics and medicines by healthcare providers. The evaluation component of the project seeks to generate evidence on the health impact, operational priorities, cost and cost-effectiveness of introducing pulse oximetry, alone or embedded into a Clinical Decision Support Algorithm (CDSA), at primary care level in LMICs, for children 0 – 59 months of age, to facilitate national and international decision-making on scale-up."
  context_title_str <- "# Context\n\n"
  baseline_str <- "Baseline visit"
  repeat_str <- "Repeat visit"
  submission_str <- "Submissions"
  enrolment_rate_str <- "Enrolment rate vs. target"
  enrolment_str <- "Enrolment"
  screening_str <- "Screening"
  withdrawal_str <- "Withdrawal"
  appendix_title <- "# Appendix\n\n"
  screening_times_str <- "Screening times"
}
```

```{r intro-text, results='asis'}
cat("\\newpage")
cat(paste0(notice_str, "\n\n", intro_str))
```

```{r setup-variables}
if (!is.null(params$facility_data)) {
  
  facility_data <- params$facility_data
  raw_day7fu_data <- params$raw_day7fu_data
  raw_hospit_data <- params$raw_hospit_data
  raw_day28fu_data <- params$raw_day28fu_data
  raw_withdrawal_data <- params$raw_withdrawal_data
  wfa_data <- params$wfa_data
  
} else {
  
  ruODK::ru_setup(
    svc = Sys.getenv("ODKC_SVC"),
    un = Sys.getenv("ODKC_UN"),
    pw = Sys.getenv("ODKC_PW"),
    tz = Sys.getenv("TZ"),
    verbose = TRUE # Can be switched to TRUE for demo or debugging
  )

  # List of projects visible with the credentials `ODKC_UN` and `ODKC_PW`
  odkc_project_list <- ruODK::project_list()$id

  rctls_pid <- Sys.getenv("TIMCI_PILOT_RCTLS_PID")
  wd_fid <- Sys.getenv("TIMCI_WD_FID")
  problem_fid <- Sys.getenv("TIMCI_PROBLEM_FID")
  
  rctls_pp <- Sys.getenv("TIMCI_RCTLS_PP")
  

  # RCT / LS environment variables
  crf_facility_fid <- Sys.getenv("TIMCI_CRF_FACILITY_FID")
  crf_day7_fid <- Sys.getenv("TIMCI_CRF_DAY7_FID")
  crf_hospit_fid <- Sys.getenv("TIMCI_CRF_HOSPIT_FID")
  if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania" || Sys.getenv('TIMCI_COUNTRY') == "India") {
    crf_day28_fid <- Sys.getenv("TIMCI_CRF_DAY28_FID")
  }
  crf_wfa_fid <- Sys.getenv("TIMCI_WEEKLY_FA_FID")

  #######################
  # Load TIMCI ODK data #
  #######################

  # List of forms visible in the RCT / LS project
  rct_ls_form_list <- ruODK::form_list(pid = rctls_pid)$fid

  # Load facility data
  print("Load facility data")

  raw_facility_zip <- ruODK::submission_export(local_dir = tempdir(),
                                               pid = rctls_pid,
                                               fid = crf_facility_fid,
                                               pp = rctls_pp)
  print(raw_facility_zip)
  raw_facility_data <- timci::extract_data_from_odk_zip(raw_facility_zip, paste0(crf_facility_fid,".csv"))
  facility_data <- timci::process_facility_data(raw_facility_data)
  pii <- timci::extract_enrolled_participants(facility_data)[[2]]
  
}

# Extract personally identifiable data
pii <- timci::extract_enrolled_participants(facility_data)[[2]]

# Merge facility generic info with facility data
facility_data <- merge(facility_data, params$research_facilities[, c("deviceid", "facility_name")], by.x = 'device_id', by.y = 'deviceid', all.x = TRUE)
```

```{r process-facility-data, results='asis'}
start_date <- NULL
end_date <- NULL
if (nrow(facility_data) > 0) {
  start_date <- min(facility_data$date_visit)
  end_date <- max(facility_data$date_visit)
  week_nb <- ceiling(difftime(as.Date(end_date), as.Date(start_date) - 1,units = "weeks"))
  days_nb <- sum(!lubridate::wday(seq(as.Date(start_date), as.Date(end_date), "days")) %in% c("7", "1"))
  if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
    cat(paste0("Ce rapport couvre la période du **", start_date, "** (début de l'étude) au **", end_date, "** (semaine **", week_nb, "** de l'étude) pour le **Sénégal**."))
  } else {
    cat(paste0("This report covers the period from **", start_date, "** (study start) to **", end_date, "** (week **", week_nb,"** of the study) for **", Sys.getenv('TIMCI_COUNTRY'), "**."))
  }
}
```

```{r context-title, results = "asis"}
cat(context_title_str)
```

```{r context-load-facilities, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  facilities <- params$research_facilities[, c("lvl2", "facility_id", "facility_name")]
  facilities <- facilities[!duplicated(facilities$facility_id), ]
} else{
  facilities <- params$research_facilities[, c("lvl2", "facility_id", "facility_name", "type")]
  facilities <- facilities[!duplicated(facilities$facility_id), ]
}
```

```{r context-display-facilities, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  # Sort by district and rename columns
  facility_disp <- facilities %>%
    dplyr::arrange(lvl2) %>%
    dplyr::rename('District sanitaire' = 'lvl2',
                  'ID' = 'facility_id',
                  'Poste de santé' = 'facility_name')
} else{
  # Sort by district then type of facility
  facility_disp <- facilities %>%
    dplyr::arrange(lvl2, type) %>%
    dplyr::rename('District' = 'lvl2',
                  'ID' = 'facility_id',
                  'Facility' = 'facility_name',
                  'Type' = 'type')
  
}
facility_nb <- nrow(facilities)
if (Sys.getenv('TIMCI_COUNTRY') == 'Tanzania' || Sys.getenv('TIMCI_COUNTRY') == 'Kenya') {
  facilities$type <- tolower(facilities$type)
  hc_nb <- nrow(facilities %>% filter(type == "health center"))
  dispensary_nb <- nrow(facilities %>% filter(type == "dispensary"))
  cat(paste0(facility_nb, " research facilities, among which ", hc_nb, " health centres and ", dispensary_nb, " dispensaries"))
} else{
  cat(paste0(facility_nb, " research facilities"))
}
```

```{r context-facilities, results = "asis"}
facility_disp %>% knitr::kable()
```

```{r, results='asis'}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  title_str <- "# Indicateurs globaux\n\n"
  plot1_str <- "Recrutement mensuel\nvs.\ncible"
  plot2_str <- "Recrutement hebdomadaire\nvs.\ncible"
  plot3_str <- "Taux de recrutement\n(hors visites secondaires)"
} else {
  title_str <- "# Global indicators\n\n"
  plot1_str <- "Monthly enrolment\nvs.\ntarget"
  plot2_str <- "Weekly enrolment\nvs.\ntarget"
  plot3_str <- "Enrolment rate\n(excl. repeat visits)"
}
```

```{r, results = "asis"}
n_total <- 0

# Screening data
n_screened <- nrow(facility_data)
screening_data <- timci::extract_screening_data(facility_data)
visit_names <- c(screening_str)
submissions <- c(n_screened)
n_total <- n_total + n_screened

study_data <- timci::extract_all_visits(facility_data)
res <- timci::extract_enrolled_participants(facility_data)
noneligible <- timci::extract_noneligible(facility_data)

# Baseline data
baseline_data <- timci::extract_baseline_visits(study_data)
baseline_data <- merge(baseline_data, params$research_facilities[, c("deviceid", "facility_name")], by.x = 'device_id', by.y = 'deviceid', all.x = TRUE)
demog_data <- res[[1]]
n_enrolled <- nrow(demog_data)
n_enrolled7 <- nrow(dplyr::filter(demog_data, date_visit >= as.Date(Sys.Date() - 6)))
n_enrolled28 <- nrow(dplyr::filter(demog_data, date_visit >= as.Date(Sys.Date() - 27)))
visit_names <- c(visit_names, baseline_str)
submissions <- c(submissions, n_enrolled)

# Count facility submissions corresponding to repeat visits
repeat_data <- timci::extract_repeat_visits(study_data)
n_repeat <- nrow(repeat_data)
visit_names <- c(visit_names, repeat_str)
submissions <- c(submissions, n_repeat)

# Count Day 7 phone call submissions
if (!is.null(raw_day7fu_data)) {
  n_day7fu <- nrow(raw_day7fu_data)
  visit_names <- c(visit_names, "Day 7 phone call")
  submissions <- c(submissions, n_day7fu)
  n_total <- n_total + n_day7fu
}

# Count hospital visit submissions
if (!is.null(raw_hospit_data)) {
  n_hospit <- nrow(raw_hospit_data)
  visit_names <- c(visit_names, "Hospital visit")
  submissions <- c(submissions, n_hospit)
  n_total <- n_total + n_hospit
}

# Count withdrawal submissions
if (!is.null(raw_withdrawal_data)) {
  n_withdrawal <- nrow(raw_withdrawal_data)
  visit_names <- c(visit_names, withdrawal_str)
  submissions <- c(submissions, n_withdrawal)
  n_total <- n_total + n_withdrawal
}

if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania" || Sys.getenv('TIMCI_COUNTRY') == "India") {
  if (!is.null(raw_day28fu_data)) {
    n_day28fu <- nrow(raw_day28fu_data)
    visit_names <- c(visit_names, "Day 28 phone call")
    submissions <- c(submissions, n_day28fu)
    n_total <- n_total + n_day28fu
  }
}
```

```{r, results='asis'}
cat(title_str)
```

```{r, results='asis'}
#timci::text_2_plot(paste0(days_nb))
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == "Senegal") {
  wdays_str <- " jours travaillés depuis le début de la collecte de données."
} else{
  wdays_str <- " working days since the start of the data collection."
}
cat(paste0(days_nb, wdays_str))
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == "Kenya") {
  hc_enrolment_target <- 25
  dispensary_enrolment_target <- 5
  day_target <- dispensary_enrolment_target * dispensary_nb + hc_enrolment_target * hc_nb
  enrolment_target <- day_target / facility_nb
} else if (Sys.getenv('TIMCI_COUNTRY') == "Senegal") {
  enrolment_target <- 8
} else if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania") {
  hc_enrolment_target <- 16
  dispensary_enrolment_target <- 4
  day_target <- dispensary_enrolment_target * dispensary_nb + hc_enrolment_target * hc_nb
  enrolment_target <- day_target / facility_nb
} else{
  enrolment_target <- 8
}
if (Sys.getenv('TIMCI_COUNTRY') != "Tanzania" || Sys.getenv('TIMCI_COUNTRY') != "Kenya") {
  day_target <- enrolment_target * facility_nb
  if (Sys.getenv('TIMCI_COUNTRY') == "Senegal") {
    cat(paste0("Cible de recrutement quotidienne : ", enrolment_target))
  } else{
    cat(paste0("Daily enrolment target: ", enrolment_target))
  }
} else{
  cat(paste0("Daily enrolment target: ", dispensary_enrolment_target, " (dispensaries) and ", hc_enrolment_target, " (health centres), with ", enrolment_target, " as an average target if the facility type is not taken into account"))
}
```

```{r, results='asis'}
if (nrow(facility_data) > 0) {
  plot1 <- timci::plot_enrolment_gauge(n_enrolled28/(min(20, days_nb) * day_target), plot1_str, 100, 62.5, 100)
  plot2 <- timci::plot_enrolment_gauge(n_enrolled7/(min(5, days_nb) * day_target), plot2_str, 100, 62.5, 100)
  plot3 <- timci::plot_enrolment_gauge(n_enrolled/(n_screened - n_repeat), plot3_str, 100, 70, 80)
}
```

```{r, results='asis'}
day7_wmin <- 7
day7_wmax <- 10
day7_expandedwmax <- 12

day7fu_data <- NULL
if (!is.null(raw_day7fu_data)) {
  if (nrow(raw_day7fu_data) > 0) {
    day7fu_data <- timci::format_day7_data(raw_day7fu_data)[[3]]
    succ_day7fu_data <- timci::format_day7_data(raw_day7fu_data)[[1]]
    n_completed_day7fu <- sum((as.Date(succ_day7fu_data$date_day0, "%Y-%m-%d") + day7_expandedwmax) <= Sys.Date()) 
    n_valid_day7fu <- sum(((as.Date(succ_day7fu_data$date_day0, "%Y-%m-%d") + day7_expandedwmax) <= Sys.Date()) & (succ_day7fu_data$days >= day7_wmin) & (succ_day7fu_data$days <= day7_wmax)) 
  } else {
    n_completed_day7fu <- 0
    n_valid_day7fu <- 0
  }
} else {
  n_completed_day7fu <- 0
  n_valid_day7fu <- 0
}
```

```{r}
n_due_day7fu <- sum((as.Date(demog_data$date_visit, "%Y-%m-%d") + day7_expandedwmax) <= Sys.Date())
```

```{r, results='asis'}
gridExtra::grid.arrange(plot1, plot2, ncol = 2)
```

```{r, results='asis'}
gridExtra::grid.arrange(plot3, plot3, ncol = 2)
```

```{r, results='asis'}
if (n_due_day7fu > 0)
{
  # gauge plots
  plot4 <- timci::plot_enrolment_gauge(n_completed_day7fu/n_due_day7fu, "Day 7 follow-up rate", 100, 85, 95)
  plot5 <- timci::plot_enrolment_gauge(n_valid_day7fu/n_due_day7fu, "Day 7 follow-up rate\nwithin the time window", 100, 80, 90)
  gridExtra::grid.arrange(plot4, plot5, ncol = 2)
}
```

```{r, results='asis'}
day28_wmin <- 28
day28_wmax <- 32
day28_expandedwmax <- 35

if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania" || Sys.getenv('TIMCI_COUNTRY') == "India") {
  day28fu_data <- NULL
  if (!is.null(raw_day28fu_data)) {
    if (nrow(raw_day28fu_data) > 0) {
      day28fu_data <- timci::format_day28_data(raw_day28fu_data)[[3]]
      succ_day28fu_data <- timci::format_day28_data(raw_day28fu_data)[[1]]
      n_completed_day28fu <- sum((as.Date(succ_day28fu_data$date_day0, "%Y-%m-%d") + day28_expandedwmax) <= Sys.Date()) 
      n_valid_day28fu <- sum(((as.Date(succ_day28fu_data$date_day0, "%Y-%m-%d") + day28_expandedwmax) <= Sys.Date()) & (succ_day28fu_data$days >= day28_wmin) & (succ_day28fu_data$days <= day28_wmax)) 
    } else {
      n_completed_day28fu <- 0
      n_valid_day28fu <- 0
    }
  } else {
    n_completed_day28fu <- 0
    n_valid_day28fu <- 0
  }
  
  n_due_day28fu <- sum((as.Date(demog_data$date_visit, "%Y-%m-%d") + day28_expandedwmax) <= Sys.Date())
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania" || Sys.getenv('TIMCI_COUNTRY') == "India") {
  if (n_due_day28fu > 0) {
    # gauge plots
    plot7 <- timci::plot_enrolment_gauge(n_completed_day28fu/n_due_day28fu, "Day 28 follow-up rate", 100, 85, 95)
    plot8 <- timci::plot_enrolment_gauge(n_valid_day28fu/n_due_day28fu, "Day 28 follow-up rate\nwithin the time window", 100, 80, 90)
    gridExtra::grid.arrange(plot7, plot8, ncol = 2)
  }
}
```

```{r submissions-1, results = "asis"}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("# Soumissions\n\n")
  cat("## Nombre total de soumissions par formulaire\n\n")
} else {
  cat("# Submissions\n\n")
  cat("## Total number of submissions per form\n\n")
}

visit_names <- c(visit_names, "All")
submissions <- c(submissions, n_total)

visits <- data.frame(visit_names, submissions) 
visits %>% knitr::kable(col.names = c("Visit", "N"))
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Recrutement hebdomadaire\n\n")
} else {
  cat("## Weekly enrolment\n\n")
}
```

```{r, results = "asis"}
if (!is.null(baseline_data) & length(baseline_data) > 0 & nrow(baseline_data) > 0) {
  val <- day_target * 5
  p <- timci::generate_week_bar_plot(date_vec = baseline_data$date_visit,
                                     date_min = as.Date(start_date),
                                     date_max = as.Date(Sys.Date() + 1),
                                     ylbl = paste0(enrolment_str),
                                     rref = val,
                                     relative = FALSE)
  plot(p)
}
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("### Fréquentation hebdomadaire des postes\n\n")
} else {
  cat("### Clinic weekly attendance\n\n")
}
```

```{r, results = "asis"}
if (!is.null(wfa_data) & length(wfa_data) > 0 & nrow(wfa_data) > 0) {
  wfa_data$week <- as.Date(cut(as.Date(wfa_data$date),
                          breaks = "week",
                          start.on.monday = TRUE))
  ggplot2::ggplot(wfa_data, aes(x = week, y = nb_children_seen)) +
    geom_bar(stat = "identity", fill = "#7dbbd6", width = 7) +
    ggplot2::scale_x_date(limits = c(as.Date(start_date), as.Date(Sys.Date() + 1)),
                          breaks = "1 week",
                          date_labels = "%y.%m.%d") +
    theme(panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_blank(),
          axis.text.x = element_text(angle = 45, hjust = 1),
          panel.background = element_blank())
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Nombre de soumissions au cours des 30 derniers jours\n\n")
} else {
  cat("## Number of submissions during the last 30 days\n\n")
}
```

```{r, results='asis'}
w <- 29
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("### Recrutement quotidien\n\n"))
} else {
  cat(paste0("### Daily enrolment\n\n"))
}
if (nrow(baseline_data) > 0) {
  timci::generate_day_bar_plot(date_vec = baseline_data$date_visit,
                               date_min = as.Date(Sys.Date() - w),
                               date_max = as.Date(Sys.Date() + 1),
                               ylbl = enrolment_str,
                               rref = day_target)
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("### Visites primaires et secondaires\n\n"))
} else {
  cat(paste0("### Baseline and repeat visits\n\n"))
}

# Frequency
if (nrow(baseline_data) > 0) {
  timci::generate_day_cumbar_plot(list(noneligible$date_visit,
                                       baseline_data$date_visit,
                                       repeat_data$date_visit),
                                  c("Non-eligible", baseline_str, repeat_str),
                                  as.Date(Sys.Date() - w),
                                  as.Date(Sys.Date() + 1),
                                  ylbl = submission_str)
} else{
  cat('N/A\n\n')
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Cartes thermiques calendaires\n\n")
  cat("### Screening\n\n")
} else {
  cat("## Calendar heatmaps\n\n")
  cat("### Screening\n\n")
}

timci::generate_calendar_heatmap(facility_data, date_visit)
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("### Visites primaires\n\n")
} else {
  cat("### Baseline visits\n\n")
}

if (nrow(baseline_data) > 0) {
  timci::generate_calendar_heatmap(baseline_data, date_visit)
}
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Heure de début du screening\n\n")
} else {
  cat("## Screening start times\n\n")
}
```

```{r, results = "asis"}
timci::generate_time_hist_plot(facility_data, screening_times_str)
```

To be completed (track submissions that are not submitted on the same day)

```{r, results = "asis"}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("# Participants\n\n"))
} else {
  cat(paste0("# Participants\n\n"))
}
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("## Eligibilité\n\n"))
} else {
  cat(paste0("## Eligibility\n\n"))
}

all <- data.frame(facility_data)
all$sickness[is.na(all$sickness)] <- 0
all$inpatient[is.na(all$inpatient)] <- 0
all$consult_reason[is.na(all$consult_reason)] <- 0
all$cg_eligibility[is.na(all$cg_eligibility)] <- 0
all$prev_enrl[is.na(all$prev_enrl)] <- 0
all$repeat_consult[is.na(all$repeat_consult)] <- 0
all$yg_infant <- ifelse(all$yg_infant == 0, "2-59m", "0-2m")

if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("### Âge\n\n")
} else {
  cat("### Age\n\n")
}
age_statistics <- list(
  "Facility" = list(
    "First day of life" = ~qwraps2::n_perc(age_excl == 1, pres),
    "1 - 59 days" = ~qwraps2::n_perc(age_incl == 1 & yg_infant == "0-2m", pres),
    "2 - 59 months" = ~qwraps2::n_perc(age_incl == 1 & yg_infant == "2-59m", pres),
    "Above 59 months" = ~qwraps2::n_perc(age_incl == 0, pres)
    )
)
st <- qwraps2::summary_table(all, age_statistics)
st1 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), age_statistics)
print(t(cbind(st, st1)))
```

```{r, results = "asis"}
all <- all %>% filter(age_incl == 1 & age_excl == 0)

if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("### Enfants malades\n\n")
} else {
  cat("### Sick children\n\n")
}
sickness_statistics <- list(
  "Facility" = list(
    "Sick children" = ~qwraps2::n_perc(sickness == 1, pres),
    "Other children" = ~qwraps2::n_perc(sickness == 0, pres)
    )
)
st <- qwraps2::summary_table(all, sickness_statistics)
st1 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), sickness_statistics)
print(t(cbind(st, st1)))
```

```{r, results = "asis"}
sick <- all %>% filter(sickness == 1)
nonsick <- all %>% filter(sickness == 0)
all <- sick
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("#### Principal motif de consultation pour les enfants malades\n\n")
} else {
  cat("#### Primary reason for consultation for sick children\n\n")
}
sick_reason_statistics <- list(
  "Facility" = list(
    "Sickness" = ~qwraps2::n_perc(consult_reason == 1, pres),
    "Trauma" = ~qwraps2::n_perc(consult_reason == 2 & sickness == 1, pres),
    "Immunisation" = ~qwraps2::n_perc(consult_reason == 3 & sickness == 1, pres),
    "Monitoring" = ~qwraps2::n_perc(consult_reason == 4 & sickness == 1, pres)
    )
)
st <- qwraps2::summary_table(all, sick_reason_statistics)
st1 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), sick_reason_statistics)
print(t(cbind(st, st1)))
```

```{r, results = "asis"}
all <- nonsick
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("#### Principal motif de consultation pour les autres enfants\n\n")
} else {
  cat("#### Primary reason for consultation for other children\n\n")
}
reason_statistics <- list(
  "Facility" = list(
    "Trauma" = ~qwraps2::n_perc(consult_reason == 2 & sickness == 0, pres),
    "Immunisation" = ~qwraps2::n_perc(consult_reason == 3 & sickness == 0, pres),
    "Monitoring" = ~qwraps2::n_perc(consult_reason == 4 & sickness == 0, pres),
    "Inpatient admission" = ~qwraps2::n_perc(inpatient == 1, pres)
    )
)
if (!is.null(all) & length(all) > 0 & nrow(all) > 0) {
  st <- qwraps2::summary_table(all, reason_statistics)
  st1 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), reason_statistics)
  print(t(cbind(st, st1)))
}
```

```{r, results = "asis"}
all <- sick
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("#### Âge de l'accompagnant principal\n\n")
} else {
  cat("#### Caregiver's age\n\n")
}
summary_statistics <- list(
  "Facility" = list(
    "Below 18" = ~qwraps2::n_perc(cg_eligibility == 0, pres),
    "18 and above" = ~qwraps2::n_perc(cg_eligibility == 1, pres)
    )
)
st <- qwraps2::summary_table(all, summary_statistics)
st1 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), summary_statistics)
print(t(cbind(st, st1)))
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("##### Proportion de mères adolescentes\n\n"))
} else {
  cat(paste0("##### Proportion of underaged mothers\n\n"))
}

all$underaged_mother[is.na(all$underaged_mother)] <- 0

mother_statistics <- list(
  "Mother's age" = list(
    "Below 18" = ~qwraps2::n_perc(underaged_mother == 1 | (main_cg == 1 & cg_eligibility == 0), pres),
    "18 and above" = ~qwraps2::n_perc(underaged_mother == 0 | (main_cg == 1 & cg_eligibility == 1), pres)
    )
)

st <- qwraps2::summary_table(all, mother_statistics)
if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania") {
  st1 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), mother_statistics)
  print(t(cbind(st, st1)))
} else{
  print(t(st))
}
```

```{r, results = "asis"}
all <- all %>% filter(cg_eligibility == 1)
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("#### Recrutements multiples\n\n")
} else {
  cat("#### Multiple enrolments\n\n")
}
summary_statistics <- list(
  "Facility" = list(
    "First" = ~qwraps2::n_perc(prev_enrl == 3 | prev_enrl == 98, pres),
    "Previous" = ~qwraps2::n_perc(prev_enrl == 1 | prev_enrl == 2, pres),
    "Last <= 28 days" = ~qwraps2::n_perc(repeat_consult == 1, pres),
    "Last > 28 days" = ~qwraps2::n_perc((prev_enrl == 1 | prev_enrl == 2) & repeat_consult == 0, pres)
    )
)
st <- qwraps2::summary_table(all, summary_statistics)
st1 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), summary_statistics)
print(t(cbind(st, st1)))
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("## Consentement éclairé\n\n"))
} else {
  cat(paste0("## Informed consent\n\n"))
}

all <- all %>% filter(prev_enrl == 3 | prev_enrl == 98)

consent_statistics <- list(
  "Facility" = list(
    "Consented" = ~qwraps2::n_perc(consent == 1, pres),
    "Not consented" = ~qwraps2::n_perc(consent == 0, pres)
    )
)
st <- qwraps2::summary_table(all, consent_statistics)
st1 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), consent_statistics)
print(t(cbind(st, st1)))
```
  
```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("### Causes de non-recrutement\n\n"))
} else {
  cat(paste0("### Non-enrolment causes\n\n"))
}

non_enrolment_causes <- timci::count_screening(facility_data)
nec_pie_chart <- timci::generate_pie_chart(non_enrolment_causes)
plot(nec_pie_chart)
```

```{r, results = "asis"}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("# Visite primaire\n\n"))
} else {
  cat(paste0("# Baseline visit\n\n"))
}
```

```{r contact-details-title, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Informations de contact")
} else {
  cat("## Contact details")
}
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') != 'Kenya') {
  if (!is.null(facility_data)) {
    if (nrow(facility_data) > 0) {
      
      all <- data.frame(facility_data)
      all$phone_nb[!is.na(all$phone_nb)] <- 1
      all$phone_nb[is.na(all$phone_nb)] <- 0
      all$phone_nb2[!is.na(all$phone_nb2)] <- 1
      all$phone_nb2[is.na(all$phone_nb2)] <- 0
      all$phone_nb3[!is.na(all$phone_nb3)] <- 1
      all$phone_nb3[is.na(all$phone_nb3)] <- 0
      all$cmty[is.na(all$cmty)] <- 0
      all$cmty[!is.na(all$cmty) & "hapana" %in% tolower(all$cmty)] <- 0
      all$cmty[!is.na(all$cmty) & !("hapana" %in% tolower(all$cmty))] <- 1
      all$location[all$location != '' & all$location != ' ' & all$location != 'Outside the region'] <- 1
      all$location[all$location == '' | all$location == ' ' | all$location == 'Outside the region'] <- 0
      
      phone_stats <- list(
        "Phone number" = list(
          "0" = ~qwraps2::n_perc(phone_nb == 0, 2),
          "1" = ~qwraps2::n_perc(phone_nb == 1, 2),
          "2" = ~qwraps2::n_perc((phone_nb == 1) & (phone_nb2 == 1), 2),
          "3" = ~qwraps2::n_perc((phone_nb == 1) & (phone_nb2 == 1) & (phone_nb3 == 1), 2)
          )
      )
      
      cols <- colnames(all)
      if (!is.null(all) & length(all) > 0 & nrow(all) > 0) {
        if ('district' %in% cols) {
          print(qwraps2::summary_table(dplyr::group_by(all, district), phone_stats))
        } else{
          print(qwraps2::summary_table(all, phone_stats))
        }
      }
      
      all <- all %>%
        dplyr::filter(all$phone_nb == 0)
      
      contact_details_stats <- list(
        "No phone number" = list(
          "No community contact" = ~qwraps2::n_perc((cmty == 0) & (phone_nb == 0), 2),
          "Community contact" = ~qwraps2::n_perc((cmty == 1) & (phone_nb == 0), 2),
          "Unknown residence" = ~qwraps2::n_perc((location == 0) & (phone_nb == 0), 2),
          "Known residence" = ~qwraps2::n_perc((location == 1) & (phone_nb == 0), 2)
          )
      )
  
      cols <- colnames(all)
      if (!is.null(all) & length(all) > 0 & nrow(all) > 0) {
        if ('district' %in% cols) {
          print(qwraps2::summary_table(dplyr::group_by(all, district), contact_details_stats))
        } else{
          print(qwraps2::summary_table(all, contact_details_stats))
        }
      }
      
    }
  }
}
```

```{r header-clinical-presentation, results = "asis"}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("## Oxymètre de pouls\n\n"))
} else {
  cat(paste0("## Pulse oximetry\n\n"))
}
```

```{r, results = "asis"}
if (nrow(baseline_data) > 0) {
  
  if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
    cat(paste0("### 1 - 59 jours\n\n"))
  } else {
    cat(paste0("### 1 - 59 days\n\n"))
  }
  
  all <- data.frame(baseline_data) %>% filter(yg_infant == 1)
  
  pox_statistics <- list(
    "Pulse oximetry" = list(
      "Reported" = ~qwraps2::n_perc(spo2 == 1, 2)
      )
  )
  pox_summary1 <- qwraps2::summary_table(all, pox_statistics)
  pox_summary2 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), pox_statistics)
  print(t(cbind(pox_summary1, pox_summary2)))
  
  if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
    cat(paste0("### 2-59 months\n\n"))
  } else {
    cat(paste0("### 2-59 months\n\n"))
  }
  
  all <- data.frame(baseline_data) %>% filter(yg_infant == 0)
  
  pox_statistics <- list(
    "Pulse oximetry" = list(
      "Reported" = ~qwraps2::n_perc(spo2 == 1, 2)
      )
  )
  pox_summary1 <- qwraps2::summary_table(all, pox_statistics)
  pox_summary2 <- qwraps2::summary_table(dplyr::group_by(all, facility_name), pox_statistics)
  print(t(cbind(pox_summary1, pox_summary2)))

}
```

```{r header-referrals, results = "asis"}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("## Orientation vers un centre de référence\n\n"))
} else {
  cat(paste0("## Referrals\n\n"))
}
```

```{r, results = "asis"}
if (nrow(baseline_data) > 0) {
  all <- data.frame(study_data)
  all$yg_infant <- ifelse(all$yg_infant == 0, "2-59 months", "2-59 days")
  all$referral_cg <- ifelse(!is.na(all$referral_cg), all$referral_cg, 100)
  all$referral_hf <- ifelse(!is.na(all$referral_hf), all$referral_hf, 100)
  
  summary_statistics <- list(
    "Referral (caregiver)" = list(
      "No" = ~qwraps2::n_perc(referral_cg == 0, 2),
      "Yes" = ~qwraps2::n_perc(referral_cg == 1, 2),
      "Unknown" = ~qwraps2::n_perc(referral_cg == 98, 2),
      "Declined" = ~qwraps2::n_perc(referral_cg == 97, 2),
      "Lost at exit" = ~qwraps2::n_perc(referral_cg == 100, 2)
      ),
    "Referral (registry)" = list(
      "No" = ~qwraps2::n_perc(referral_hf == 0, 2),
      "Yes" = ~qwraps2::n_perc(referral_hf == 1, 2),
      "Missing" = ~qwraps2::n_perc(referral_hf == 100, 2)
      )
  )
  referral_summary <- qwraps2::summary_table(all, summary_statistics)
  referral_summary1 <- qwraps2::summary_table(dplyr::group_by(all, yg_infant), summary_statistics)
  print(cbind(referral_summary, referral_summary1))
}
```

```{r}
if (nrow(baseline_data) > 0) {
  referral_data <- timci::extract_referrals(study_data)
  n_referrals <- nrow(referral_data)
  referral_pie_chart <- timci::generate_pie_chart(data.frame(group = c("Referred at Day 0", "Not referred at Day 0"), value = c(n_referrals, n_enrolled - n_referrals)))
  plot(referral_pie_chart)
}
```

```{r, results = "asis"}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("# Suivi à Jour 7\n\n"))
  cat(paste0("La période valable pour le suivi à Jour 7 est de **", day7_wmin, "** à **", day7_wmax, "** jours.\n\n"))
  if (n_due_day7fu > 0) {
    cat(paste0("Il y a **", n_due_day7fu, "** suivis à Jour 7 attendus aujourd'hui."))
  }
} else {
  cat(paste0("# Day 7 follow-up\n\n"))
  cat(paste0("The valid Day 7 follow-up period is **", day7_wmin, "** to **", day7_wmax, "** days.\n\n"))
  if (n_due_day7fu > 0) {
    cat(paste0("There are **", n_due_day7fu, "** Day 7 follow-ups expected today."))
  }
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Appels hebdomadaires\n\n")
} else {
  cat("## Weekly calls\n\n")
}
```

```{r, results = "asis"}
if (!is.null(raw_day7fu_data) & length(raw_day7fu_data) > 0 & nrow(raw_day7fu_data) > 0) {
  p <- timci::generate_week_bar_plot(date_vec = raw_day7fu_data$date,
                                     date_min = as.Date(start_date),
                                     date_max = as.Date(Sys.Date() + 1),
                                     ylbl = paste0(enrolment_str))
  plot(p)
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Nombre de soumissions au cours des 30 derniers jours\n\n")
} else {
  cat("## Number of submissions during the last 30 days\n\n")
}

if (!is.null(raw_day7fu_data)) {
  if (nrow(raw_day7fu_data) > 0) {
    plot(timci::generate_day_bar_plot(raw_day7fu_data$date, as.Date(Sys.Date() - w),
                                      as.Date(Sys.Date() + 1),
                                      ylbl = submission_str))
  } else{
    cat('0 submissions since the start of the study.\n\n')
  }
} else {
  cat('0 submissions since the start of the study.\n\n')
  }
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Cartes thermiques calendaires\n\n")
} else {
  cat("## Calendar heatmap\n\n")
}

if (!is.null(raw_day7fu_data)) {
  if (nrow(raw_day7fu_data) > 0) {
    timci::generate_calendar_heatmap(raw_day7fu_data, date)
  } else{
    cat('N/A\n\n')
  }
} else{
    cat('N/A\n\n')
  }
```

```{r day7-data-monitoring-title, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat("## Contrôle des données du suivi à jour 7")
} else {
  cat("## Data")
}
```

```{r, results = "asis"}
if (!is.null(day7fu_data)) {
  if (nrow(day7fu_data) > 0) {
    
    all <- data.frame(day7fu_data)
    all$cg_reached[is.na(all$cg_reached)] <- 0
    all$cg_ok[is.na(all$cg_ok)] <- 0
    all$status_day7[is.na(all$status_day7)] <- 0
    all$cure_day7[is.na(all$cure_day7)] <- 0
    
    day7_call_stats <- list(
      "Call outcome" = list(
        "Participant reached" = ~qwraps2::n_perc(cg_reached == 1, 2),
        "Valid time window" = ~qwraps2::n_perc(cg_reached == 1 & (days >= day7_wmin) & (days <= day7_wmax), 2),
        "Lost to follow-up" = ~qwraps2::n_perc((cg_reached == 1 & (cg_ok == 0 | days > day7_wmax)), 2)
        )
    )
    
    st <- qwraps2::summary_table(all, day7_call_stats)
    
    if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania") {
      st1 <- qwraps2::summary_table(dplyr::group_by(all, district), day7_call_stats)
      print(cbind(st, st1))
    } else{
      print(st)
    }
  }
}
```

```{r, results = "asis"}
if (!is.null(day7fu_data)) {
  if (nrow(day7fu_data) > 0) {
    
    all <- data.frame(succ_day7fu_data)
    day7_outcome_ss <- list(
      "Time" = list(
        "Mean (SD)" = ~qwraps2::mean_sd(days)
        ),
      "Cure" = list(
        "Known" = ~qwraps2::n_perc(cure_day7 == 1 | cure_day7 == 2 | cure_day7 == 3 | cure_day7 == 4, 2)
        ),
      "Higher level visit" = list(
        "Reported" = ~qwraps2::n_perc(hf_visit_day7 == 1 & hf_visit_type == 1, 2)
        )
    )
    print(qwraps2::summary_table(all, day7_outcome_ss))
  }
}
```

```{r, results = "asis"}
cat("\\newpage")
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("# Suivi des visites à l'hôpital\n\n"))
} else {
  cat(paste0("# Hospital follow-up\n\n"))
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
  cat(paste0("## Visite à l'hôpital\n\n"))
} else {
  cat(paste0("## Hospital visit\n\n"))
}

if (!is.null(raw_hospit_data)) {
  if (nrow(raw_hospit_data) > 0) {
    plot(timci::generate_day_bar_plot(raw_hospit_data$date, as.Date(Sys.Date() - w),
                                      as.Date(Sys.Date() + 1),
                                      ylbl = submission_str))
  } else{
    cat('0 submissions since the start of the study.\n\n')
  }
} else{
  cat('0 submissions since the start of the study.\n\n')
}
```

```{r, results = "asis"}
if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania" || Sys.getenv('TIMCI_COUNTRY') == "India") {
  cat("\\newpage")
  cat('# Day 28 follow-up\n\n')
  if (!is.null(raw_day28fu_data)) {
    if (nrow(raw_day28fu_data) > 0) {
      day28fu_data <- timci::format_day28_data(raw_day28fu_data)[[1]]
      #day28fu_data <- merge(baseline_data, day28fu_data, by = 'child_id', all.x = TRUE)
      day28fu_data <- day28fu_data %>%
        dplyr::mutate(days = as.Date(date_call) - as.Date(date_day0), na.rm = TRUE)
      
      all <- data.frame(day28fu_data)
      all$a1_contact_a4_d_1b[is.na(all$cg_ok)] <- 0
      all$o1_o1_1a[is.na(all$status_day28)] <- 0
      all$o1_o1_1[is.na(all$cure_day28)] <- 0
      all$n1_o3_1[is.na(all$hf_visit_day28)] <- 0
      
      day28_call_ss <- list(
        "Call outcome" = list(
          "Participant reached" = ~qwraps2::n_perc(cg_reached == 1, 2),
          "Valid time window" = ~qwraps2::n_perc(cg_reached == 1 & (days >= day28_wmin) & (days <= day28_wmax), 2),
          "Lost to follow-up" = ~qwraps2::n_perc((cg_reached == 1 & (cg_ok == 0 | days > day28_wmax)), 2)
          )
      )
      print(qwraps2::summary_table(all, day28_call_ss))
    }
  }
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania" || Sys.getenv('TIMCI_COUNTRY') == "India") {
  if (Sys.getenv('TIMCI_COUNTRY') == 'Senegal') {
    cat("## Appels hebdomadaires\n\n")
  } else {
    cat("## Weekly calls\n\n")
  }
  if (!is.null(raw_day28fu_data) & length(raw_day28fu_data) > 0 & nrow(raw_day28fu_data) > 0) {
  p <- timci::generate_week_bar_plot(date_vec = raw_day28fu_data$date,
                                     date_min = as.Date(start_date),
                                     date_max = as.Date(Sys.Date() + 1),
                                     ylbl = paste0(enrolment_str))
  plot(p)
}
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania" || Sys.getenv('TIMCI_COUNTRY') == "India") {
  cat('## Number of submissions during the last 30 days\n\n')
  if (!is.null(raw_day28fu_data)) {
    if (nrow(raw_day28fu_data) > 0) {
      plot(timci::generate_day_bar_plot(raw_day28fu_data$date, as.Date(Sys.Date() - w),
                                        as.Date(Sys.Date() + 1),
                                        ylbl = submission_str))
    } else {
      cat('0 submissions since the start of the study.\n\n')
    }
  } else{
    cat('0 submissions since the start of the study.\n\n')
  }
}
```

```{r, results='asis'}
if (Sys.getenv('TIMCI_COUNTRY') == "Tanzania" || Sys.getenv('TIMCI_COUNTRY') == "India") {
  cat("## Calendar heatmap\n\n")
  if (!is.null(raw_day28fu_data)) {
    if (nrow(raw_day28fu_data) > 0) {
      timci::generate_calendar_heatmap(raw_day28fu_data, date)
    } else{
      cat('N/A\n\n')
    }
  } else{
    cat('N/A\n\n')
  }
}
```

```{r appendix-title, results = "asis"}
cat("\\newpage")
cat(appendix_title)
```

```{r, results="asis"}
out <- lapply(1:nrow(facilities), function(i) {
  knitr::knit_child(
    'rct_monitoring_report_facility_sub.Rmd', envir = environment(), quiet = TRUE
  )
})
cat(unlist(out), sep = '\n')
```

```{r, results="asis"}
out <- knitr::knit_child('facility_report.Rmd', quiet = TRUE)
cat(paste(out, collapse = '\n'))
```
