\clearpage

```{r cgei-message}
write(formats2h2("Generate the caregiver exit interview subsection"), stderr())
```

`r h1_spa_cgei`

```{r spa-cgeu-condition}
n <- nrow(spa_cgei_data)
cond <- n > 0
```

**`r n`** submissions

```{r, eval = cond, results='asis', fig.cap = heatmap_cap}
timci::generate_calendar_heatmap2(spa_cgei_data,
                                  date,
                                  legendtitle = "Number of submissions")
```

```{r, results='asis', fig.cap = heatmap2_cap, fig.height = figsize}
timci::heatmap_wday_hourofday(spa_cgei_data,
                              'start')
```

```{r, results = "asis"}
all <- spa_cgei_data %>% 
  rename(referral = "g5-i4_1",
         facility_name = "fname")

summary <- list(
  "Summary" = list(
    "Yes" = ~qwraps2::n_perc(referral == 1, prec),
    "No" = ~qwraps2::n_perc(referral == 0, prec),
    "Not sure" = ~qwraps2::n_perc(referral == 98, prec),
    "Declined" = ~qwraps2::n_perc(referral == 97, prec)
    )
)
out <- format_summary_table(all, summary, facility_name)
out %>% 
  kableExtra::kbl(booktabs = TRUE,
                  linesep = "",
                  align = c("c", "c", "c", "c"),
                  caption = "Referral") %>% 
  kableExtra::kable_styling(latex_options = c("HOLD_position", "repeat_header"), font_size = table_fs) %>%
  kableExtra::row_spec(0, bold = TRUE) %>%
  kableExtra::row_spec(1, color = total_row_ft2, background = total_row_bg2, bold = TRUE) %>%
  kableExtra::row_spec(1:(nrow(out)/2) * 2, background = striped_row_bg)
```
