\newpage

`r h1_tech_info`

The template of this report (v1.0) was designed by Hélène LANGET (Swiss TPH)

```{r, results='asis', echo=FALSE}
df_session <- devtools::session_info(include_base = TRUE)
```

```{r, results='asis', echo=FALSE}
df_session_platform <- df_session$platform %>% 
  unlist(.) %>% 
  as.data.frame(.) %>% 
  tibble::rownames_to_column(.)
colnames(df_session_platform) <- c("Setting", "Value")
kableExtra::kbl(df_session_platform, 
                booktabs = TRUE, 
                align = c("l", "c")) %>% 
  kableExtra::kable_styling(latex_options = c("HOLD_position", "repeat_header", "striped"),
                            font_size = table_fs) %>%
  kableExtra::row_spec(0, bold = TRUE)
```

```{r, results='asis', echo=FALSE}
df_session_packages <- df_session$packages[c("loadedversion", "date", "source")]
colnames(df_session_packages) <- c("Loaded version", "Date", "Source")
df_session_packages %>% kableExtra::kbl(booktabs = TRUE,
                                        linesep = "",
                                        longtable = TRUE,
                                        align = "c") %>% 
  kableExtra::kable_styling(latex_options = c("HOLD_position", "repeat_header", "striped"),
                            font_size = table_fs) %>%
  kableExtra::row_spec(0, bold = TRUE)
```
