```{r default}
age_eligibility_table_cap <- "Age of the child at screening."
age_eligibility_table_gfn <- "Screening number are extracted using the device ID associated with a given facility."
all_str <- "All"
baseline_str <- "Baseline visit"
baseline_visit_title_str <- "### Baseline visits\n\n"
calendar_heatmap_title_str <- "## Calendar heatmap\n\n"
consent_cap <- "Informed consent"
consultation_nonsick_cap <- "Primary reason for consultation for non sick children."
consultion_sick_cap <- "Primary reason for consultation for sick children."
day7_phone_call_str <- "Day 7 phone call"
eligibility_str <- "Individual child inclusion:\\begin{itemize}\\item Children 0 – 59 months for whom caregivers provide consent;\\item Consulting for an illness, or reported to be unwell when attending for a routine visit (e.g. vaccination, growth or chronic disease monitoring).\\end{itemize}Individual child exclusion:\\begin{itemize}\\item Children in the immediate post-natal period or first day of life;\\item Attending for a consultation related to trauma only (including new and follow-up presentations for burns, injuries, wounds);\\item Admitted within an inpatient part of the facility (including neonates delivered at the facility admitted with their mother);\\item Enrolled in the study within the preceding 28 days at any study facility.\\end{itemize}"
eligibility_title <- "# Eligibility\n\n"
enrolment_rate_str <- "Enrolment rate vs. target"
enrolment_str <- "Enrolment"
facility_cap <- "List of research facilities"
intro_str <- "The overall goal of the Tools for the Management of Childhood Illness (TIMCI) project is to reduce morbidity and mortality in sick children attending primary care facilities, while supporting the rational and efficient use of diagnostics and medicines by healthcare providers. The evaluation component of the project seeks to generate evidence on the health impact, operational priorities, cost and cost-effectiveness of introducing pulse oximetry, alone or embedded into a Clinical Decision Support Algorithm (CDSA), at primary care level in LMICs, for children 0 – 59 months of age, to facilitate national and international decision-making on scale-up."
hospital_submission_str <- "Hospital visit"
multi_rec_cap <- "Multiple enrolments"
nonenrolment_cap <- "Non-enrolment causes"
notice_str <- "\\begin{center}\\textbf{For internal use only. Do not share outside research teams. Tables and figures are generated from raw databases, not from the cleaned databases, and findings of this report can therefore be slightly different from those of the formal statistical analysis.}\\end{center}"
plot0_str <- "Total enrolment\nvs. target sample size"
plot1_str <- "Monthly enrolment\nvs. monthly target"
plot2_str <- "Weekly enrolment\nvs. weekly target"
plot3_str <- "Enrolment rate\n(excl. repeat visits)"
plot4_str <- "Day 7 follow-up rate"
plot5_str <- "Day 7 follow-up rate\nwithin the statistical window"
pox_title_str <- "## Pulse oximetry\n\n"
referral_title_str <- "## Referrals\n\n"
repeat_str <- "Repeat visit"
sample_size_str <- "Target\nsample size"
screening_str <- "Screening"
screening_times_str <- "Screening times"
sick_cap <- "Sickness at screening"
submission_table_cap <- "Number of visits."
submission_str <- "Submissions"
title_str <- "# Global indicators\n\n"
u18_mother_cap <- "Proportion of underaged mothers if the mother is not the main caregiver"
wdays_str <- "Working days\nsince start"
weekly_enrolment_hdr2 <- "## Weekly enrolment\n\n"
withdrawal_str <- "Withdrawal"
enrolment_target_str <- "Daily\nenrolment target"

heatmap_cap <- "Calendar heatmap"
heatmap2_cap <- "Day/hour heatmap"

appendix_title <- "# Appendix\n\n"
h1_context <- "# Context\n\n"
h1_day0_visit <- "# Baseline (day 0) visit\n\n"
h1_participants <- "# Participants\n\n"
h1_processmapping <- "# Process mapping\n\n"
h1_spa_cgei <- "# Caregiver exit interview\n\n"
h1_spa_fa <- "# Facility assessment\n\n"
h1_spa_hcpi <- "# Healthcare provider interview\n\n"
h1_spa_sco <- "# Sick child observation protocol\n\n"
h1_tech_info <- "# Report generation information\n\n"
h1_timeflow <- "# Time-flow\n\n"

h2_calendar_heatmap <- "## Calendar heatmap\n\n"
h2_clinical_presentation <- "## Clinical presentation\n\n"
h2_diagnoses <- "## Diagnoses\n\n"
h2_research_operations <- "## Research operations\n\n"

h3_pneumonia <- "### Pneumonia\n\n"

tcap_age_category <- "Age category."
tcap_danger_signs <- "Danger signs."
tcap_all_completion <- "Number of participants with complete follow-up visits."
tcap_day7fu_completion <- "Number of participants with a complete Day 7 follow-up."
tcap_day28fu_completion <- "Number of participants with a complete Day 28 follow-up."
tcap_hospitalisation_completion <- "Number of participants with a documented hospitalisation."
tcap_hospit_visit_completion <- "Number of participants with a documented hospital visit."
tcap_missing_symptoms <- "Number of participants with an incomplete clinical presentation."
tcap_monthly_enrolment <- "Monthly recruitment since start."
tcap_observed_danger_signs <- "Observed danger signs."
tcap_phone_numbers <- "Number of participants with a phone number."
tcap_pneumonia <- "Pneumonia"
tcap_scanned_manual <- "Types of entry for participant QR codes."
tcap_weekly_enrolment <- "Weekly recruitment since start."

fcap_up_maps <- "TIMCI districts in Uttar Pradesh"
```

```{r french, eval = (Sys.getenv('TIMCI_COUNTRY') == 'Senegal'), results = "asis"}
cat("\\selectlanguage{french}")
  
age_eligibility_table_cap <-"Âge de l'enfant lors du screening."
age_eligibility_table_gfn <- "Le nombre de screenings est déterminé à l'aide de l'ID de la tablette associée à un poste donné."
all_str <- "Total"
baseline_str <- "Visite primaire"
baseline_visit_title_str <- "### Visites primaires\n\n"
calendar_heatmap_title_str <- "## Cartes thermiques calendaires\n\n"
consent_cap <- "Consentement éclairé"
consultation_nonsick_cap <- "Principal motif de consultation pour les enfants non malades."
consultion_sick_cap <- "Principal motif de consultation pour les enfants malades."
day7_phone_call_str <- "Appel téléphonique à Jour 7"
eligibility_str <- "Individual child inclusion:\\begin{itemize}\\item Children 0 – 59 months for whom caregivers provide consent;\\item Consulting for an illness, or reported to be unwell when attending for a routine visit (e.g. vaccination, growth or chronic disease monitoring).\\end{itemize}Individual child exclusion:\\begin{itemize}\\item Children in the immediate post-natal period or first day of life;\\item Attending for a consultation related to trauma only (including new and follow-up presentations for burns, injuries, wounds);\\item Admitted within an inpatient part of the facility (including neonates delivered at the facility admitted with their mother);\\item Enrolled in the study within the preceding 28 days at any study facility.\\end{itemize}"
eligibility_title <- "# Eligibilité\n\n"
enrolment_rate_str <- "Taux de recrutement par rapport à l'objectif"
enrolment_str <- "Recrutement"
facility_cap <- "Liste des poste de recherche"
intro_str <- "L’objectif global du projet TIMCI (Outils pour la prise en charge intégrée des maladies de l’enfant) est de réduire la morbidité et la mortalité chez les enfants malades dans les structures de soins primaires, tout en soutenant l’utilisation rationnelle et efficace des moyens diagnostiques et des médicaments par les prestataires de soins de santé. Le volet évaluation du projet vise à apporter des preuves de l’impact de l’introduction de l’oxymètre de pouls, associé à un Algorithme d’aide à la décision clinique (CDSA), sur la santé, les priorités opérationnelles, le coût et l’analyse cout-efficacité modélisée dans le contexte des soins primaires, pour les enfants âgés de 0 à 59 mois des pays à revenu faible ou intermédiaire (PRFI), en vue de faciliter la prise de décision et la mise à l’échelle aux niveaux national et international."
hospital_submission_str <- "Hospitalisation"
multi_rec_cap <- "Recrutements multiples"
nonenrolment_cap <- "Causes de non-recrutement"
notice_str <- "\\begin{center}\\textbf{Pour usage interne uniquement. Ne pas partager en dehors des équipes recherche. Les tableaux et les figures sont générés à partir des bases de données brutes, et non à partir des bases de données nettoyées, et les résultats de ce rapport peuvent donc être légèrement différents de ceux de l'analyse statistique formelle.}\\end{center}"
plot0_str <- "Recrutement total\nvs. taille d'échantillon cible"
plot1_str <- "Recrutement mensuel\nvs. cible mensuelle"
plot2_str <- "Recrutement hebdomadaire\nvs. cible hebdomadaire"
plot3_str <- "Taux de recrutement\n(hors visites secondaires)"
plot4_str <- "Taux de suivi à Jour 7"
plot5_str <- "Taux de suivi à Jour 7\ndans la fenêtre statistique"
pox_title_str <- "## Oxymètre de pouls\n\n"
referral_title_str <- "## Orientation vers un centre de référence\n\n"
repeat_str <- "Visite secondaire"
sample_size_str <- "Taille d'échantillon cible : "
screening_str <- "Screening"
screening_times_str <- "Heures de screening"
sick_cap <- "Enfant malade lors du screening"
submission_str <- "Soumissions"
submission_table_cap <- "Nombre de visites."
title_str <- "# Indicateurs globaux\n\n"
u18_mother_cap <- "Proportion de mères adolescentes si la mère n'est pas l'accompagnant principal"
wdays_str <- " jours travaillés depuis le début de la collecte de données."
weekly_enrolment_hdr2 <- "## Recrutement hebdomadaire\n\n"
withdrawal_str <- "Retrait"
enrolment_target_str <- "Cible de recrutement quotidienne"

heatmap_cap <- "Carte thermique calendaire"
heatmap2_cap <- "Carte thermique jour/heure"

appendix_title <- "# Annexe\n\n"
h1_context <- "# Contexte\n\n"
h1_day0_visit <- "# Visite primaire (Jour 0)\n\n"
h1_participants <- "# Participants\n\n"
h1_processmapping <- "# Cartographie des processus\n\n"
h1_spa_cgei <- "# Entretien de sortie avec l'accompagnant\n\n"
h1_spa_fa <- "# Evaluation du poste\n\n"
h1_spa_hcpi <- "# Entretien avec le prestataire de soins\n\n"
h1_spa_sco <- "# Observation de la consultation de l'enfant malade\n\n"
h1_tech_info <- "# Informations sur la génération du rapport\n\n"
h1_timeflow <- "# Flux temporels\n\n"

h2_calendar_heatmap <- "## Carte thermique calendaire\n\n"
h2_clinical_presentation <- "## Présentation clinique\n\n"
h2_diagnoses <- "## Diagnostics\n\n"
h2_research_operations <- "## Aspects operationnels de la recherche\n\n"

h3_pneumonia <- "### Pneumonie\n\n"

tcap_age_category <- "Catégorie d'âge."
tcap_danger_signs <- "Nombre de participants présentant un ou plusieurs signes de danger."
tcap_day7fu_completion <- "Nombre de participants ayant achevé leur suivi à Jour 7."
tcap_hospitalisation_completion <- "Nombre de participants ayant leur hospitalisation documentée."
tcap_hospit_visit_completion <- "Nombre de participants ayant leur visite à un niveau supérieur de la pyramide de soins documentée."
tcap_missing_symptoms <- "Nombre de participants présentant un tableau clinique incomplet."
tcap_monthly_enrolment <- "Recrutement mensuel depuis le début de l'étude."
tcap_observed_danger_signs <- "Signes de danger observés."
tcap_phone_numbers <- "Nombre de participants ayant un numéro de téléphone."
tcap_pneumonia <- "Pneumonie"
tcap_scanned_manual <- "Types d'entrée pour les codes QR des participants."
tcap_weekly_enrolment <- "Recrutement hebdomadaire depuis le début de l'étude."
```
